WIP: test utils revamp
JuliaGaussianProcesses/KernelFunctions.jl pull request #159
Opened 2020-08-30 18:22 UTC by willtebbutt

Introduces and applies a large number of consistency tests.

The advantage of running these tests is that we can be fairly sure that new kernels are at least self-consistent, and fully implement our interface.

The advantage of producing a new `TestUtils` module is that if someone implements a new kernel outside of `KernelFunctions`, they can straightforwardly test that the kernel obeys our interface.

This can't be merged until the following PRs are merged:

- #154 
- #158

2020-09-02 13:02 UTC, sharanry reviewed
I was going through this to understand the new testing strategy. Looks great! But, have a few doubts. :)

2020-09-02 13:39 UTC, theogf commented on src/test_utils.jl
> +    @assert length(x0) ≠ length(x2)
Aren't the two vectors of different size and therefore should be checked?

2020-09-02 13:39 UTC, willtebbutt commented on src/test_utils.jl
> +    @assert length(x0) ≠ length(x2)
Indeed it has!

2020-09-02 13:43 UTC, willtebbutt commented on src/test_utils.jl
> +function test_interface(rng::AbstractRNG, k::Kernel, T::Type{<:Real}; kwargs...)
Right. So this functionality is meant to just test common cases -- we definitely _can_ test them when the element type is non-real, we just don't know how to automatically generate candidate tests.

So if you wanted to test some arbitrary input type, or some type of `AbstractVector` that's not a `Vector`, `ColVecs`, or `RowVecs`, you would manually construct the inputs and invoke the method on line 30.

My goal here was to make it so that 95% of the time you can just say "test all of the usual things" really easily, but retain the flexibility to do specific things if you need to.

2020-09-02 13:43 UTC, willtebbutt commented on src/test_utils.jl
> +const FDM = FiniteDifferences.central_fdm(5, 1)
Haha I'm not really sure. It generally seems to work well 🤷

2020-09-02 13:44 UTC, willtebbutt commented on src/test_utils.jl
> +function test_ADs(kernelfunction, args = nothing; ADs = [:Zygote, :ForwardDiff, :ReverseDiff], dims = [3, 3])
This seems like a good proposal. It's out of scope in this PR though -- I've just copied the AD tests.

2020-09-07 20:22 UTC, devmotion commented on src/transform/lineartransform.jl
> +_map(t::LinearTransform, x::AbstractVector{<:Real}) = ColVecs(t.A * collect(x'))
Why is this needed? For AD?

2020-09-07 20:24 UTC, devmotion commented on src/test_utils.jl
> +using LinearAlgebra
```suggestion
using FiniteDifferences
using LinearAlgebra
```

2020-09-07 20:38 UTC, willtebbutt commented on src/transform/lineartransform.jl
> +_map(t::LinearTransform, x::AbstractVector{<:Real}) = ColVecs(t.A * collect(x'))
Actually no. I forget precisely which kernel it was that was causing problems, but somewhere this was breaking.

I should probably write a test that properly isolates the issue...

2020-09-08 08:40 UTC, theogf submitted a review, later dismissed

2020-09-21 16:45 UTC, willtebbutt commented
Moved some tests back to `test/test_utils.jl` because they introduce additional deps, and I would like to avoid this.

2020-09-21 20:03 UTC, willtebbutt commented
@theogf could you comment on the `GammaRationalQuadraticKernel` implementation? It appears to suffer from the same issues that the `GammaExponentialKernel` had prior to #158 , and was recently mentioned in #170 .

What are your thoughts on how it should be modified? Currently the test produce covariance matrices with negative eigenvalues, so something needs to be modified. Would you mind taking a look?

2020-09-21 20:11 UTC, willtebbutt commented
@sharanry the `NeuralNetworkKernel` implementation appears to be inconsistent between various implementations. Would you be able to pull this branch and take a look? I believe that you were the last one to look at that code.

2020-09-21 20:28 UTC, devmotion commented
Along these lines, I think it would make sense to check in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/744419e49e278ef74ec127f861ea7f42f18246e8/src/basekernels/exponential.jl#L64 that `0 < γ <= 2` (alternatively, one could use the SqEuclidean distance and force `γ` to `(0, 1]` - but I guess it was changed to Euclidean on purpose in the previous PR to be more in line with common parameterizations; as an additional option, one could just store/use `γ/2` internally).

2020-09-21 21:07 UTC, willtebbutt commented
> as an additional option, one could just store/use γ/2 internally

This is what I was thinking to be honest. There definitely seem to be computational / numerical advantages to sticking with `SqEuclidean` over `Euclidean` wherever possible.

2020-09-22 09:30 UTC, theogf commented
To be honest I think most of the code legacy is from `MLKernels.jl`. I don't mind them being modified... I think the issue is that with `gamma` up, the function becomes very quickly flat around 0, so you end up with a singular matrix...

2020-09-22 09:48 UTC, devmotion commented
It's not only a numerical problem though: for any Hilbertian distance `|.|` (such as the Euclidean norm on standard Euclidean vector spaces), mathematically the function `k(x, y) = exp(-|x-y|^s)` is positive definite if and only if `0 < s <= 2`.

2020-09-22 20:39 UTC, willtebbutt commented
Actually @theogf do you have a reference for the Gamma RQ kernel? Thinking about it I've not seen it before.

2020-09-22 20:41 UTC, theogf commented
It's also MLKernels legacy https://www.github.com/trthatcher/MLKernels.jl/tree/master/src%2Fkernelfunctions%2Fmercer%2Frationalquadratic.jl

2020-09-22 20:45 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +        @check_args(GammaRationalQuadraticKernel, γ, γ > zero(Tγ), "γ > 0")
```suggestion
        @check_args(GammaRationalQuadraticKernel, γ, zero(γ) < γ <= 2 * one(γ), "0 < γ <= 2")
```

2020-09-22 21:40 UTC, willtebbutt commented
Tests are now passing locally.

Assuming that CI passes, all that remains is to assess whether the changes that I made to the rational quadratic and gamma rational quadratic kernels are satisfactory. If so, I propose to bump the patch version and merge.

2020-09-24 09:24 UTC, willtebbutt commented
@theogf what are your thoughts on this? Note that I've rejected your previous review because I've made changes to `RationalQuadratic` that need another round of review 🙂

2020-09-24 10:22 UTC, theogf commented on src/test_utils.jl
> +function test_interface(
I am not a native speaker so I might miss the meaning but I find `test_interface` to be a right name, it sounds to me that the function is going to create a test interface, not run tests.
Shouldn't it be something like `test_kernel` instead?

2020-09-24 10:24 UTC, theogf commented on src/test_utils.jl
> +    @test all(eigvals(Matrix(kernelmatrix(k, x0))) .> -atol)
I know that this should be true, but I think that might be a test being too hard, most kernels will need some noise on the diagonal to be properly PD

2020-09-24 10:24 UTC, theogf commented on src/test_utils.jl
> +    @test all(eigvals(Matrix(kernelmatrix(k, x0))) .> -atol)
Oh now I see that you allow negative values

2020-09-24 11:24 UTC, willtebbutt commented on src/test_utils.jl
> +function test_interface(
`test` in `test_interface` is  verb in this context, so `test_interface` means "test the interface". Is that clearer?

2020-09-24 11:36 UTC, devmotion commented on src/test_utils.jl
> +    @test all(eigvals(Matrix(kernelmatrix(k, x0))) .> -atol)
An (IMO simpler) alternative:
```suggestion
    @test eigmin(Matrix(kernelmatrix(k, x0))) > -atol
```

2020-09-24 11:37 UTC, theogf reviewed
I just put a few comments (sorry for the single comments, I messed up).

You really did an amazing titan job! That looks really good!

Also should we have tests on `test_utils` itself? Making sure that it goes wrong for a wrongly defined kernel?

2020-09-24 11:37 UTC, theogf commented on test/kernels/kernelsum.jl
> +        x->KernelSum(SqExponentialKernel(),LinearKernel(c= x[1])), rand(1);
```suggestion
        x->KernelSum(SqExponentialKernel(), LinearKernel(c=x[1])), rand(1);
```

2020-09-24 11:38 UTC, theogf commented on src/test_utils.jl
> +function test_interface(
Ok got it!

2020-09-24 15:49 UTC, willtebbutt commented on src/test_utils.jl
> +
Hmm I'm reluctant to do this in this PR. The user has plenty of feedback when the tests fail in the way that the test sets are printed, and I personally prefer to minimise output during the running of tests.

2020-09-24 16:07 UTC, willtebbutt commented
For some reason I can't reply to this directly:

> Has this issue been solved? That would be great to avoid the allocation

No, unfortunately not. Would you be open to me opening a separate issue about it and pressing ahead with getting this PR merged?

2020-09-24 16:52 UTC, willtebbutt commented
> Also should we have tests on test_utils itself? Making sure that it goes wrong for a wrongly defined kernel?

Hmmm maybe. As with the above, I wonder whether we could postpone this to a future PR where we introduce some proper test fakes or something? This is already quite large :S

2020-09-25 10:47 UTC, willtebbutt commented
> Hmmm maybe. As with the above, I wonder whether we could postpone this to a future PR where we introduce some proper test fakes or something? This is already quite large :S

@theogf thoughts on this? (Sorry for being pushy -- just keen to get this merged so that I can press ahead with my Stheno.jl / TemporalGPs.jl integration plan)

2020-09-25 10:49 UTC, theogf commented
Sorry yeah sure, we can do this later! Let's just keep an issue open for this

2020-09-25 10:55 UTC, willtebbutt commented
> Sorry yeah sure, we can do this later! Let's just keep an issue open for this

Great. I'll open an issue about those two things. Then we're good to go?

2020-09-25 17:21 UTC, willtebbutt commented
If someone is happy to approve, I'll get this merged after a patch bump.

2020-09-25 17:33 UTC, devmotion requested changes

2020-09-25 17:33 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +        @check_args(RationalQuadraticKernel, α, α > one(T), "α > 1")
I don't think `α` has or should be restricted to `α > 1`. Every non-negative `α` is fine, isn't it?

Additionally, we could think about defining it as
```
κ(x, y) = (1 + ||x − y||² / (2 * α))^(-α)
```
such that the Gaussian kernel is retrieved in the limit as `α` goes to infinity (see, e.g., https://www.cs.toronto.edu/~duvenaud/cookbook/).

2020-09-25 17:34 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +        @check_args(RationalQuadraticKernel, α, α > one(T), "α > 1")
Oh I just saw that you actually changed it to the suggested form - it seems the docstring is outdated then.

2020-09-25 17:37 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +        @check_args(RationalQuadraticKernel, α, α > one(T), "α > 1")
Maybe for consistency reasons, the same changes should be applied to the Gamma rational quadratic kernel as well? There still the form without the additional 2 is used, and the parameter is also restricted to values larger than 1.

2020-09-25 17:47 UTC, willtebbutt commented on src/basekernels/rationalquad.jl
> +        @check_args(RationalQuadraticKernel, α, α > one(T), "α > 1")
Docstring and dof-constraints now fixed.

> Maybe for consistency reasons, the same changes should be applied to the Gamma rational quadratic kernel as well?

I thought about doing this, but the `GammaExponential` kernel _doesn't_ use the divide-by-2 convention, because it's not really used anywhere in the literature. Since the Gamma RQ is constructed from that kernel, it feels more appropriate to me to leave this one _without_ the divide-by-2 convention.

> such that the Gaussian kernel is retrieved in the limit as α goes to infinity

One the subject of this, please note the tests -- they now include various dof->infinity consistency checks for both RQ and Gamma-RQ kernels :)

2020-09-25 18:04 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +        @check_args(RationalQuadraticKernel, α, α > one(T), "α > 1")
Yep, I agree with your opinion on the Gamma rational quadratic kernel, I just assumed it's good to bring it up now.

I like these additional tests!

2020-09-25 18:07 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +    RationalQuadraticKernel(; α=2.0)
Is it common to use `α = 2`? Something like `α = 1` seems simpler, and is actually used as the default value by e.g. [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.RationalQuadratic.html).

2020-09-25 18:10 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +        ;alpha::Tα=2.0, gamma::Tγ=2.0, α::Tα=alpha, γ::Tγ=gamma,
I guess
```suggestion
        ;alpha::Tα=2.0, gamma::Tγ=2, α::Tα=alpha, γ::Tγ=gamma,
```
would be more performant in the default case? The question here is also if we should use `alpha = 1` as
default value.

2020-09-25 18:11 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +        ;alpha::Tα=2.0, gamma::Tγ=2.0, α::Tα=alpha, γ::Tγ=gamma,
Although probably, since we divide gamma by 2 anyway in the computation it doesn't matter.

2020-09-25 18:11 UTC, willtebbutt commented on src/basekernels/rationalquad.jl
> +    RationalQuadraticKernel(; α=2.0)
Hmmm good question. I really hadn't thought too much about this and wasn't overly fussed. I worry that 1 will yield a kernel with very long-range correlations (I'm just thinking about what a students-t with dof 1 looks like -- I think they coincide in this case).

I can't say that I'm overly fussed overall, so happy to change to 1 from 2 if you would prefer.

2020-09-25 18:19 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +    RationalQuadraticKernel(; α=2.0)
I don't have a strong opinion on this, so do whatever you think is more reasonable. Just noticed this when I compared it with the parameter choices in scikit-learn, and was wondering why we use 2 here.

2020-09-25 18:20 UTC, willtebbutt commented on src/basekernels/rationalquad.jl
> +        ;alpha::Tα=2.0, gamma::Tγ=2.0, α::Tα=alpha, γ::Tγ=gamma,
Hmmm I wonder whether this is what you want. Generally speaking, if you're using this kernel you probably don't want the `Integer` parameter value, otherwise you would be using the `RationalQuadraticKernel`. My opinion is that making this parameter a float by default probably does make sense as a consequence of this.

2020-09-25 18:23 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +        ;alpha::Tα=2.0, gamma::Tγ=2.0, α::Tα=alpha, γ::Tγ=gamma,
Makes sense.

2020-09-25 18:39 UTC, willtebbutt commented on src/basekernels/rationalquad.jl
> +    RationalQuadraticKernel(; α=2.0)
I think I'm going to leave as-is for the sake of this PR. More than happy for this to be changed in a subsequent PR though.

2020-09-25 18:41 UTC, devmotion approved these changes

2020-09-25 19:40 UTC, merged