Add @boundscheck for MOInput and  remove explicit definitions of length and iterate
JuliaGaussianProcesses/KernelFunctions.jl pull request #169
Opened 2020-09-18 10:49 UTC by sharanry

Removing unneeded definitions and using `@boundscheck` macro based on discussion in https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/30

2020-09-18 10:58 UTC, devmotion commented on src/mokernels/moinput.jl
> +    @boundscheck if ind <= 0 || ind > length(inp)
As discussed in https://docs.julialang.org/en/v1/devdocs/boundscheck/, this should just be
```suggestion
    @boundscheck checkbounds(inp, ind)
```
and the function has to be inlined for `@inbounds` to have any effect.

2020-09-18 10:58 UTC, devmotion commented on src/mokernels/moinput.jl
> +    @boundscheck if ind <= 0 || ind > length(inp)
In particular the custom error in the next lines should be removed.

2020-09-18 11:04 UTC, devmotion commented on src/mokernels/moinput.jl
>  function Base.getindex(inp::MOInput, ind::Integer)
```suggestion
@inline function Base.getindex(inp::MOInput, ind::Integer)
```

2020-09-23 17:20 UTC, devmotion commented on src/mokernels/moinput.jl
> +    return (inp.x[ind], out_dim::Int)
```suggestion
    return inp.x[ind], out_dim
```

2020-09-24 15:06 UTC, devmotion commented on src/mokernels/moinput.jl
>  function Base.getindex(inp::MOInput, ind::Integer)
This is required to force inlining of the function inside of `@inbounds`, according to the [docs](https://docs.julialang.org/en/v1/devdocs/boundscheck/#Eliding-bounds-checks) (and therefore the shown example also contains an `@inline` annotation):

> The @boundscheck(...) macro marks blocks of code that perform bounds checking. When such blocks are inlined into an @inbounds(...) block, the compiler may remove these blocks.

2020-09-26 11:22 UTC, devmotion requested changes
IMO `MOInput` requires more changes, similar to those discussed for `MOOutput`, but maybe they should go into another PR (e.g., the parent type should be changed to `AbstractVector{Tuple{T,Int}}` which defines a concrete element type and probably `iterate` should be removed).

In any case, it would be good to address https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/169/files#r494395330 before merging this PR.

2020-09-26 11:22 UTC, devmotion commented on src/mokernels/moinput.jl
>  Base.size(inp::MOInput) = (inp.out_dim * size(inp.x, 1),)
To be consistent with the definition of the indexing operation, this should probably be
```suggestion
Base.size(inp::MOInput) = (inp.out_dim * length(inp.x),)
```

2020-09-26 11:26 UTC, devmotion commented on src/mokernels/moinput.jl
>  Base.iterate(inp::MOInput) = (inp[1], 1)
Just noticed that the title of the PR explicitly says "...remove explicit definitions of length and iterate" but `iterate` is still implemented. Is there a reason for it?

2020-09-27 12:55 UTC, sharanry commented on src/mokernels/moinput.jl
>  Base.iterate(inp::MOInput) = (inp[1], 1)
I had to add it back because the default iterate for `AbstractVector{Tuple{Any,Int}}` is not what we want. It produces a couple of tests fail.

```julia
  Expression: iterate(mgpi) == (mgpi[1], 1)
   Evaluated: (([0.008457582224595583, 0.41464287382643517, 0.40664694052473127, 0.9330052885761637, 0.49389515633005887], 1), (Base.OneTo(12), 1)) == (([0.008457582224595583, 0.41464287382643517, 0.40664694052473127, 0.9330052885761637, 0.49389515633005887], 1), 1)

  Expression: iterate(mgpi, 2) == (mgpi[3], 3)
   Evaluated: (([0.7413131597666685, 0.5768240627991614, 0.6903596228103408, 0.18912000772418436, 0.8404194534198497], 1), (2, nothing)) == (([0.3674929338482975, 0.31972403013388906, 0.2344192068115616, 0.9842115504995159, 0.44655713080439274], 1), 3)

```

2020-09-27 15:28 UTC, devmotion commented on src/mokernels/moinput.jl
>  Base.iterate(inp::MOInput) = (inp[1], 1)
I think we should just remove the implementation and adjust the tests :slightly_smiling_face: The values are correct and the states are due to the standard implementation in base, which works for linear and cartesian indexing (and according to the comments is fast for linear indexing): https://github.com/JuliaLang/julia/blob/4165fddaeb4c85c6a16ccc2fc47b33376081ed31/base/abstractarray.jl#L1043-L1047

2020-09-28 11:19 UTC, devmotion commented on test/mokernels/moinput.jl
> +    @test iterate(mgpi, 2) == (mgpi[2], (2, nothing))
I don't think we should test internals that are implemented in Julia base. Maybe more reasonable would be something like
```
@test [xi for xi in x] == ...
```

2020-09-29 04:56 UTC, sharanry commented
@devmotion do you think it is okay to merge this or do you suggest any other changes?

2020-09-29 06:01 UTC, devmotion commented
Looks good mainly, just two questions:
- What is the motivation for introducing `moinput`? It seems in contrast to `mooutput` there is no alternative implemented that doesn't return a `MOInput` instance?
- The difference between `MOInput` and `MOOutput` is mainly that the first one's elements are tuples where the second element corresponds to the output dimension, right?

2020-09-29 06:50 UTC, sharanry commented
>  What is the motivation for introducing `moinput`? It seems in contrast to `mooutput` there is no alternative implemented that doesn't return a `MOInput` instance?

I wanted it to be similar to `moutput`. Mixed use of capitals just seemed very non-intuitive to me. I want to avoid usage like 
```julia
X, Y = MOInput(ColVecs(x), out_dim), moutput(y)
```

> The difference between MOInput and MOOutput is mainly that the first one's elements are tuples where the second element corresponds to the output dimension, right?

This is one aspect of it. Additionally, one can think of `MOInput` to emulate repetition of inputs for each output dimension. For example N inputs are viewed through `MOInput` as `out_dim x N` inputs without allocating any additional memory. Whereas, `MOutput` emulates flattening of the outputs from size `(out_dim, N)` to vector of length `out_dim x N`.

2020-09-29 09:12 UTC, devmotion commented
> I wanted it to be similar to moutput. Mixed use of capitals just seemed very non-intuitive to me.

Seems reasonable. In this case I suggest to not export `MOInput` anymore though.

2020-09-29 09:15 UTC, willtebbutt commented on src/mokernels/moinput.jl
> +    moinput(x::AbstractVector, out_dim::Int)
I think this should probably be underscore-separated: `mo_input`.

2020-10-08 12:09 UTC, sharanry commented
@devmotion @willtebbutt Is this okay to merge?

2020-10-08 16:33 UTC, devmotion commented on src/KernelFunctions.jl
> +export MOInput, mo_input
I'd suggest to remove `MOInput` from the exports:
```suggestion
export mo_input
```

2020-10-10 15:49 UTC, devmotion commented on src/mokernels/mo_input.jl
> +A data type to accomodate modelling multi-dimensional output data.
```suggestion
A data type to accomodate modelling multi-dimensional input data.
```

2020-10-10 15:49 UTC, devmotion commented on src/mokernels/mo_input.jl
> +Return `MOInput` to accomodate modelling multi-dimensional output data.
IMO this docstring is not very helpful, since also the one of `MOInput` is not more informative. At some point we should clarify what these methods/types are actually doing.

2023-09-15 19:50 UTC, willtebbutt commented
Stale, so closing. Please re-open if updates are provided.

2023-09-15 19:50 UTC, closed without merging