Fix issue with gradient from kerneldiagmatrix
JuliaGaussianProcesses/KernelFunctions.jl pull request #208
Opened 2020-12-09 18:48 UTC by theogf

Following #203 I changed map(x->k(x,x), x) to k.(x,x) and I removed the method for `TransformedKernel`, we don't gain anything (I think) since we don't reuse the transformed input. This solves the issue on #203

2020-12-09 18:53 UTC, willtebbutt commented
This makes me a little nervous. The benefit of calling `kerneldiagmatrix` from inside `kerneldiagmatrix`, is that if there's a specialised method in the base kernel for `kerneldiagmatrix` (e.g. return all zeros), that still gets called.

I would have thought that a better solution would be to require `_map(κ.transform, x)` to be defined for each transform, so that it happens efficiently.

2020-12-09 19:01 UTC, willtebbutt commented
I'm actually surprised that this problem is happening at all. Looking into it now.

2020-12-14 16:31 UTC, devmotion commented on test/utils_AD.jl
> +const FDM = FiniteDifferences.central_fdm(5, 1)
This file seems to contain a lot of code that already exists in `test_utils.jl`?

2020-12-14 16:42 UTC, theogf commented on test/utils_AD.jl
> +const FDM = FiniteDifferences.central_fdm(5, 1)
That's possible there is some overlapping. @willtebbutt wrote the Test_Utils module, could you comment on it?

2020-12-14 16:42 UTC, theogf commented
@willtebbutt It seems your fix on defining methods for SimpleKernel fixed the issue. I added AD test for kerneldiagmatrix now

2020-12-14 16:45 UTC, devmotion commented on test/utils_AD.jl
> +const FDM = FiniteDifferences.central_fdm(5, 1)
It's basically exactly the same apart from the `testdiagfunction`, isn't it? https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/master/test/test_utils.jl

2020-12-14 16:51 UTC, theogf commented on test/utils_AD.jl
> +const FDM = FiniteDifferences.central_fdm(5, 1)
Yeah and in `test/test_utils.jl` there is more AD stuff.
I think it needs a different PR to solve this though

2020-12-14 16:58 UTC, devmotion commented on test/utils_AD.jl
> +const FDM = FiniteDifferences.central_fdm(5, 1)
Hmm I don't understand - can't you just add the `testdiagfunction` parts to `test/test_utils.jl`? The `test/utils_AD.jl` file in this PR does not exist and seems to duplicate quite many things.

2020-12-14 17:01 UTC, devmotion commented on test/utils_AD.jl
> +const FDM = FiniteDifferences.central_fdm(5, 1)
You also did not include or load the new `test/utils_AD.jl` file in the tests.

2020-12-14 17:03 UTC, theogf commented on test/utils_AD.jl
> +const FDM = FiniteDifferences.central_fdm(5, 1)
Oh you're right I got confused. I did not see that utils_AD.jl was not used...

2020-12-14 17:14 UTC, devmotion commented on test/test_utils.jl
> +            if !(args === nothing)
It doesn't really matter but it feels a bit more natural to write:
```suggestion
            if args !== nothing
```

2020-12-14 17:14 UTC, devmotion commented on test/test_utils.jl
> +            if !(args === nothing)
```suggestion
            if args !== nothing
```

2020-12-14 18:14 UTC, devmotion commented
It seems the error is not fixed?

2020-12-15 11:48 UTC, theogf commented
> It seems the error is not fixed?

Yep, I tried @willtebbutt suggestion but it does not solve the problem...

2020-12-15 11:52 UTC, willtebbutt commented on src/matrix/kernelmatrix.jl
> +    return map(x -> κ(x, x), x)
```suggestion
    return kerneldiagmatrix(κ, x, x)
```

2020-12-15 11:52 UTC, willtebbutt commented on src/matrix/kernelmatrix.jl
> +    return map(d -> kappa(κ, d), map(metric(κ), x, y))
```suggestion
    return map(d -> kappa(κ, d), colwise(metric(κ), x, y))
```
The solution isn't currently working because `map` utilises `getindex` on `x` and `y` to compute the distances. You would need to use an implementation that doesn't do this -- `Distances.colwise` would satisfy this.

2020-12-15 11:55 UTC, theogf commented on src/matrix/kernelmatrix.jl
> +    return map(d -> kappa(κ, d), map(metric(κ), x, y))
Oh I see, where `Distances.colwise` is not defined for vectors right now, but we could have our own implementation.

2020-12-15 11:56 UTC, willtebbutt commented on src/matrix/kernelmatrix.jl
> +    return map(d -> kappa(κ, d), map(metric(κ), x, y))
Yeah, we'll probably want to do what we did with `pairwise` and roll our own to avoid type-pirating as you say.

2020-12-15 14:01 UTC, theogf commented on src/matrix/kernelmatrix.jl
> +    return map(d -> kappa(κ, d), map(metric(κ), x, y))
This still does not work, or maybe my implementation of `colwise` is not what you thought about

2020-12-15 14:29 UTC, willtebbutt commented on src/distances/pairwise.jl
> +end
Yup, you'll need to define `colwise` specifically for `RowVecs` and `ColVecs`

2020-12-15 16:14 UTC, theogf commented on src/distances/pairwise.jl
> +end
`Distances.colwise` is mutating arrays :cry:

2021-03-16 15:03 UTC, theogf commented
Back to this annoying problem!
So I seem to have found a solution (for Zygote at least), but it has a small touch of piracy :D.
`Distances.jl` accepts now iterators/generator for `pairwise` which makes our task easier. However it's not the case for `colwise` which only takes matrices... I dispatched correctly for `ColVecs` and `RowVecs` using `x.X` and `x.X'` but then for the generic case of `AbstractVector` I had to implement our own version -> type piracy... I will anyway open an issue on Distances.jl to see if it is possible to add the option.

2021-03-16 15:24 UTC, devmotion commented
I guess the correct way would be to define our own `colwise` function, analogously to `pairwise`. And then fall back to the definitions in Distances where it is possible.

2021-03-17 16:00 UTC, devmotion commented on src/distances/pairwise.jl
> +    d.(x, x)
I think
```suggestion
    return map(d, x, x)
```
would be simpler here - there's no need for the broadcasting machinery since the inputs have the same dimension.

2021-03-17 16:02 UTC, devmotion commented on src/matrix/kernelmatrix.jl
> +    return map(d -> kappa(κ, d), colwise(metric(κ), x))
BTW one could use `Base.Fix1` here instead of the custom closure:
```suggestion
    return map(Base.Fix1(kappa, κ), colwise(metric(κ), x))
```

2021-03-17 16:03 UTC, devmotion commented on src/zygote_adjoints.jl
> +end
Could we add ChainRules-definitions instead of rules for Zygote? ChainRules also avoids the Zygote-weirdness with `nothing`.

2021-03-17 16:05 UTC, theogf commented on src/matrix/kernelmatrix.jl
> +    return map(d -> kappa(κ, d), colwise(metric(κ), x))
When was `Fix1` introduced? I thought it was a recent addition

2021-03-17 16:06 UTC, theogf commented on src/zygote_adjoints.jl
> +end
Completely agree with this, but should it be in this PR or should it be done in another one?

2021-03-17 16:36 UTC, devmotion commented on src/matrix/kernelmatrix.jl
> +    return map(d -> kappa(κ, d), colwise(metric(κ), x))
It exists since Julia 0.7.0-alpha: https://github.com/JuliaLang/julia/pull/26708

2021-03-17 16:37 UTC, theogf commented on src/matrix/kernelmatrix.jl
> +    return map(d -> kappa(κ, d), colwise(metric(κ), x))
Haha while watching the Julia PR I saw this PR reference appearing :p

2021-03-17 16:58 UTC, theogf commented on src/zygote_adjoints.jl
> +end
I ended up rewriting `rrule` wherever it was possible

2021-03-22 14:54 UTC, theogf commented
Oh man this starts to be exhausting :tired_face: 

So now moving to `rrule` should solve most of the issues, **EXCEPT** that as pointed by @willtebbutt in https://github.com/JuliaDiff/ChainRulesCore.jl/issues/239#issuecomment-713560336, since `Zygote` defines already some `@adjoint` for `Distances.pairwise` and therefore the `rrule` we define for our own types are completely ignored...

@willtebbutt should I make a PR to Zygote to pass the `Distances.jl` rule under the `ChainRules` syntax?

2021-03-22 15:20 UTC, willtebbutt commented
Eurgh, yeah, this _is_ turning into a pain. Thanks for persevering.

I would be pro- that and would be willing to both review a PR and push for it to be merged.

2021-03-22 16:19 UTC, theogf commented
My bad, removing adjoints from Zygote does not help. @willtebbutt Could you have a quick look at `chainrules.jl` (previously `zygote_adjoints.jl`) ? It seems my `rrule` are completely ignored by Zygote...

2021-03-22 16:27 UTC, theogf commented
Yep I mostly restart the REPL everytime. I am evaluating `test/basekernels/constant.jl` because it needs the `Delta` `rrule`

2021-03-22 16:40 UTC, theogf commented
OMG I am so stupid, I found the problem...
Since I was doing `using ChainRulesCore`, `rrule` was not overloaded but just created as a new local function...

2021-03-22 16:54 UTC, willtebbutt commented
Classic -- happens to me all of the time!

2021-03-22 16:58 UTC, devmotion commented on src/chainrules.jl
> +    if dims == 1
Does this check lead to any type inference problems?

2021-03-22 16:59 UTC, devmotion commented on src/chainrules.jl
> +        return (nothing, Δ' .* Y, Δ' .* X)
```suggestion
        return NO_FIELDS, Δ' .* Y, Δ' .* X
```

2021-03-22 17:01 UTC, devmotion commented on src/chainrules.jl
> +        return (r=-2Δ .* abs2.(sind) ./ s.r,), Δ * gradx, -Δ * gradx
It seems `-2 .* abs2.(sind) ./ s.r` could be precomputed? I'm not completely familiar with the latest updates in ChainRules but AFAIK one should use `Composite` here?

2021-03-22 17:02 UTC, devmotion commented on src/chainrules.jl
> +    gradx = 2π .* cospi.(d) .* sind ./ (s.r .^ 2)
Do we depend on StatsFuns? If yes, one could also use
```suggestion
    gradx = twoπ .* cospi.(d) .* sind ./ (s.r .^ 2)
```

2021-03-22 17:03 UTC, devmotion commented on src/chainrules.jl
> +        return throw(error("In slow method"))
What's the advantage over just
```suggestion
        return error("in slow method")
```
?

2021-03-22 17:03 UTC, devmotion commented on src/chainrules.jl
> +    d = (x - y)
```suggestion
    d = x - y
```

2021-03-22 17:06 UTC, theogf commented on src/chainrules.jl
> +    if dims == 1
Do you mean the `if dims == 1` ?

2021-03-22 17:12 UTC, devmotion commented on src/chainrules.jl
> +    if dims == 1
Yes. Mainly because you return two different functions depending on the value of `dim`, so I wonder if it messes up type inference and if it would be better to move the check inside the pullback function.

2021-03-22 17:49 UTC, theogf commented on src/chainrules.jl
> +        return throw(error("In slow method"))
That's legacy code from Stheno.jl so I don't know but I guess you're right.

2021-03-22 18:17 UTC, theogf commented
Ok things look a bit better :)
@willtebbut Can you have a look at the `rrule` for the `Row/ColVecs` constructors? I had to define a new pullback for `Composite` types and it looked a bit different. Tests seem to like it but I am not sure it's entirely correct.

2021-03-22 18:31 UTC, devmotion commented on src/chainrules.jl
> +    end
This is definitely type unstable, isn't it? Maybe we could write instead:
```suggestion
    if !iszero(D)
        Δ ./= D
    end
    return D, dot(Δ, Δx) - dot(Δ, Δy)
```

2021-03-22 18:34 UTC, devmotion commented on src/chainrules.jl
> +function ChainRulesCore.rrule(::typeof(Distances.evaluate), s::Delta, x::AbstractVector, y::AbstractVector)
Didn't Distances.jl switch to callable structs and forwards `evaluate(dist, x, y)` to `dist(x, y)`? In this case it would be better to define adjoints for `dist(x, y)` instead of `evaluate` (IIRC I changed this in the implementation of Zygote a while ago to fix a bug).

2021-03-22 18:34 UTC, theogf commented on src/chainrules.jl
> +    end
Ah yeah that's a good idea. But anyway it's not used right now.
Both ForwardDiff and ReverseDiff return `NaN` for the `Euclidean` metric, which is correct but highly undesirable. I can fix it for ReverseDiff but any idea how I can do it for ForwardDiff?

2021-03-22 18:35 UTC, devmotion commented on src/chainrules.jl
> +)
Same here, maybe it would be better to define an adjoint for
```suggestion
function ChainRulesCore.rrule(
    s::DotProduct, x::AbstractVector, y::AbstractVector
)
```
(if we overload `DotProduct`)

2021-03-22 18:38 UTC, theogf commented on src/chainrules.jl
> +function ChainRulesCore.rrule(::typeof(Distances.evaluate), s::Delta, x::AbstractVector, y::AbstractVector)
That's because we use `evaluate` here : https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/ae78b7337eced196f8f90e656252cf12b287391b/src/generic.jl#L9

But this could be changed as well.

And this is also because `DotProduct` is not a metric so we would need to add all the same machinery once #194 is finished.

2021-03-22 18:44 UTC, theogf commented on src/chainrules.jl
> +function ChainRulesCore.rrule(::typeof(Distances.evaluate), s::Delta, x::AbstractVector, y::AbstractVector)
Ah yeah you're right, I will also change it in the rest of the code.

2021-03-23 13:13 UTC, theogf commented
:tada:  **ALL TESTS ARE PASSING LOCALLY!** :tada:

Ok so for the Euclidean problem I solved it by having:

`colwise(::PreMetric, x) = zeros(length(x))` because that's the definition

while defining a different one for `DotProduct` and `Delta` (which are not proper distance, this should be solved in #194

2021-03-23 14:09 UTC, theogf commented
@devmotion The reviewdog is not happy with the EOF... Is that anything that can be solved?

2021-03-23 15:07 UTC, theogf commented
![image](https://user-images.githubusercontent.com/11480067/112168814-e88f0b80-8bf1-11eb-9a3a-b7348eff17cd.png)

2021-03-23 17:58 UTC, devmotion commented
Ah I see.

I just ran JuliaFormatter locally and it fails since the files do not end with a newline character (it updates the two files that reviewdog complains about). So indeed the format check fails correctly. The only problem seems to be that Github suggestions do not work properly for these suggestions with an additional newline character. Therefore I guess in this case unfortunately one has to fix the files manually, either locally (with or without JuliaFormatter) or directly on Github.

2021-03-23 20:00 UTC, theogf commented
Current fails are just random, it's ready to review/merge

2021-03-23 20:09 UTC, devmotion requested changes
Looks good overall! I had a few questions, and I think we should use ChainRulesTestUtils to properly test the ChainRules definitions.

2021-03-23 20:09 UTC, devmotion commented on src/chainrules.jl
> +    RowVecs_pullback(Δ::Composite) = (NO_FIELDS, Δ.X)
```suggestion
    RowVecs_pullback(Δ::Composite{<:RowVecs}) = (NO_FIELDS, Δ.X)
```

2021-03-23 20:09 UTC, devmotion commented on src/chainrules.jl
> +    ColVecs_pullback(Δ::AbstractMatrix) = (Δ,)
When do these occur? And maybe one could restrict it to `NamedTuple{(:X,)}`?

2021-03-23 20:09 UTC, devmotion commented on src/chainrules.jl
> +    RowVecs_pullback(Δ::AbstractMatrix) = (Δ,)
Same question here :slightly_smiling_face:

2021-03-23 20:09 UTC, devmotion commented on src/chainrules.jl
> +end
Maybe keep these in a separate `zygoterules.jl` file?

2021-03-23 20:09 UTC, devmotion commented on src/chainrules.jl
> +        δa = (B_Bᵀ * a_b) * Δ
Maybe it would make sense to use a `Thunk` for `δa` (and therefore implicitly `B_Bᵀ`)?

2021-03-23 20:09 UTC, devmotion commented on src/chainrules.jl
> +        return (qmat=(a_b * a_b') * Δ,), δa, -δa
Should this again be a `Composite` instead?

2021-03-23 20:09 UTC, devmotion commented on src/distances/pairwise.jl
> +end
It's a bit unfortunate that the return type might be different from `colwise(metric, x, x)`.

2021-03-23 20:09 UTC, devmotion commented on test/chainrules.jl
> +@testset "Chain Rules" begin
We should use ChainRulesTestUtils for testing ChainRules definitions.

2021-03-24 10:54 UTC, theogf commented on src/chainrules.jl
> +    if dims == 1
But I don't think the `dims` argument passed to the pullback ?

2021-03-24 13:55 UTC, theogf commented on src/chainrules.jl
> +        return (qmat=(a_b * a_b') * Δ,), δa, -δa
I have no idea... There is no documentation about this...

2021-03-24 13:56 UTC, theogf commented on test/chainrules.jl
> +@testset "Chain Rules" begin
I am trying to add tests using `test_rrule` and `test_frule` but I get tons of errors (I think because of the structs). I would leave it aside for now...

2021-03-24 15:26 UTC, devmotion commented on src/chainrules.jl
> +        return (qmat=(a_b * a_b') * Δ,), δa, -δa
I guess @willtebbutt might know this?

2021-03-24 15:27 UTC, devmotion commented on test/chainrules.jl
> +@testset "Chain Rules" begin
If it's too much work (and I mean there are already many changes in this PR) I would be fine with addressing it in a separate PR. Just make sure to open an issue that reminds us about it :slightly_smiling_face:

2021-03-24 15:29 UTC, theogf commented on src/chainrules.jl
> +        return (qmat=(a_b * a_b') * Δ,), δa, -δa
Also it's legacy and I don't think we even have a kernel with the SqMahalanobis distance :laughing:

2021-03-24 16:28 UTC, devmotion commented on src/chainrules.jl
> +        return (qmat=(a_b * a_b') * Δ,), δa, -δa
IIRC there was another definition where I thought one could/should use Composite.

2021-03-24 17:18 UTC, theogf commented on test/chainrules.jl
> +@testset "Chain Rules" begin
Yeah I would prefer to finally finish with this. Note that these rules are anyway tested through the kernels (so we are kinda safe). But of course we should add them in a later state

2021-03-24 19:57 UTC, devmotion commented on src/chainrules.jl
> +        return (qmat=(a_b * a_b') * Δ,), δa, @thunk(-δa)
I think there might not be any benefit from putting the gradient of `b` in a thunk since the construction of the closure might be too expensive. Moreover, it seems one can safely assume that `qmat` is symmetric since the definition of `pairwise!` in Distances uses this property (see https://github.com/JuliaStats/Distances.jl/issues/174). After reading https://juliadiff.org/ChainRulesCore.jl/dev/gradient_accumulation.html, my suggestion would be:
```suggestion
        a_b = a - b
        ∂qmat = InplaceableThunk(
            @thunk((a_b * a_b') * Δ),
            X̄ -> mul!(X̄, a_b, a_b', true, Δ),
        )
        ∂a = InplaceableThunk(
            @thunk((2 * Δ) * dist.qmat * a_b),
            X̄ -> mul!(X̄, dist.qmat, a_b, true, 2 * Δ),
        )
        ∂b = InplaceableThunk(
            @thunk((-2 * Δ) * dist.qmat * a_b),
            X̄ -> mul!(X̄, dist.qmat, a_b, true, -2 * Δ),
        )
        return Composite{typeof(dist)}(qmat = ∂qmat), ∂a, ∂b
```

2021-03-25 11:31 UTC, theogf commented
Should we make a patch version bump followed by a minor version bump where we remove the deprecation warnings?

2021-03-25 11:59 UTC, willtebbutt commented
Sorry @theogf , which deprecations are you referring to?

2021-03-25 12:05 UTC, theogf commented
`kerneldiagmatrix` vs `kernelmatrix_diag` and some others like `degree` vs `d` etc...

2021-03-25 12:11 UTC, willtebbutt commented
Oh I see. Yeah, patch followed by minor release seems reasonable to me.

2021-03-25 14:11 UTC, devmotion approved these changes
Looks good to me :+1:

2021-03-25 14:12 UTC, merged