Introduce JuliaFormatter with style=blue
JuliaGaussianProcesses/KernelFunctions.jl pull request #220
Opened 2021-01-09 16:55 UTC by st--

Addressing #219, this is the diff from calling JuliaFormatter's `format("src")` using `style = "blue"`.

2021-01-09 17:52 UTC, willtebbutt commented
I like this a lot 👍

2021-01-09 18:23 UTC, devmotion commented on src/KernelFunctions.jl
> +    @require Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e" begin
It seems a bit inconsistent to add whitespace here, compared with the conventions for keyword arguments - is this according to BlueStyle or a JuliaFormatter thing?

2021-01-09 18:32 UTC, devmotion commented
Did the merge commit revert any changes from JuliaFormatter? I guess it would be good to add the Github action for checking the format in this PR as well to be sure it passes.

2021-01-09 18:48 UTC, st-- commented on .github/workflows/ci.yml
> +  format:
Separate from the others as format-testing should be independent of the host/version matrix and it seems more sensible to only run it once (and then it's easier to distinguish format failure from the "regular" tests)

2021-01-09 19:49 UTC, devmotion requested changes

2021-01-09 19:49 UTC, devmotion commented on .github/workflows/ci.yml
> +        args: -v .
To me it seems this approach should not be used anymore. The julia-format repo says that the legacy Docker version that is used here is deprecated and it is "advised you use the format check example above". So instead we should adapt https://github.com/julia-actions/julia-format/blob/master/workflows/format_check.yml, as suggested in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/219#issuecomment-757319168.

2021-01-09 22:22 UTC, st-- commented on .github/workflows/ci.yml
> +        args: -v .
Ah, I had misunderstood the README. Updated accordingly.

2021-01-09 22:23 UTC, st-- commented on .github/workflows/ci.yml
> +        args: -v .
A bit unfortunate that's not made clearer; the https://github.com/domluna/JuliaFormatter.jl README might as well point directly to the format_check.yml then ...

2021-01-09 22:28 UTC, willtebbutt commented on .github/workflows/ci.yml
> +        args: -v .
Hmm yeah, you do have to dig around a bit to figure out what the right thing to do is, and I'm still not really sure I understand what's going on -- it seems like it's otherwise a well-documented package. Would be great if one of you could open an issue about it.

2021-01-09 23:04 UTC, devmotion commented on .github/workflows/ci.yml
> +          version: ${{ matrix.julia-version }}
This seems unnecessarily complicated and uses an outdated Julia version, I suggest:
```suggestion
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
```

2021-01-09 23:05 UTC, devmotion commented on .github/workflows/ci.yml
> +
```suggestion
```

2021-01-09 23:12 UTC, devmotion commented on .github/workflows/ci.yml
> +          julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="0.12.2"))'
I don't like that the version number has to be updated manually if there is a new version of JuliaFortmatter. We could just install the latest version but this means we would end up with breaking changes without realizing. Ideally, we would add a Project.toml file in some directory and be notified about breaking releases by CompatHelper.

2021-01-09 23:15 UTC, st-- commented on .github/workflows/ci.yml
> +        args: -v .
https://github.com/julia-actions/julia-format/issues/15

2021-01-09 23:18 UTC, st-- commented on .github/workflows/ci.yml
> +          julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="0.12.2"))'
I agree, that'd be nice. I'm not sure how you'd go about sorting it out with the Project.toml (feel free to make those changes on this branch or a separate PR). I do think it's overall better to pin the version of the formatter, as otherwise it can be hard to figure out how exactly to get the local formatter be in sync with the cloud format-checker..

2021-01-09 23:18 UTC, st-- commented on .github/workflows/ci.yml
> +  format:
```suggestion
  format-check:
```

2021-01-09 23:25 UTC, devmotion commented on .github/workflows/ci.yml
> +          julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="0.12.2"))'
> I'm not sure how you'd go about sorting it out with the Project.toml

Similar to the package, tests, and documentation, we can specify the SemVer-compatible versions in a separate project environment. CompatHelper will automatically create a PR on Github if a new breaking release is available (we are not notified about non-breaking releases).

> it can be hard to figure out how exactly to get the local formatter be in sync with the cloud format-checker.

I think specifying the version that we use in a project environment is the best we can do. We can't control which version of JuliaFormatter developers use in their editors or install globally but if they load our project environment it will always be compatible.

2021-01-10 00:04 UTC, devmotion commented on src/KernelFunctions.jl
> +        color=Base.info_color(),
Break formatting on purpose to test action:
```suggestion
        color = Base.info_color(),
```

2021-01-10 00:14 UTC, devmotion commented on src/KernelFunctions.jl
> +        color=Base.info_color(),
Seems to work, tests failed correctly.

2021-01-10 01:05 UTC, devmotion commented
I simplified the Github action and pushed some changes, but since I got involved now someone else has to approve the PR.

2021-01-10 16:41 UTC, nickrobinson251 commented on src/KernelFunctions.jl
> +    @require Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e" begin
I agree. I suspect this is a JuliaFormatter (or CSTParser) issue

2021-01-10 19:28 UTC, theogf approved these changes

2021-01-11 10:42 UTC, theogf commented
@devmotion I think you still need to indicate that your change requests have been satisfied.

2021-01-11 10:44 UTC, devmotion approved these changes

2021-01-11 10:47 UTC, merged