Rename kerneldiagmatrix[!] -> kernelmatrix_diag[!]
JuliaGaussianProcesses/KernelFunctions.jl pull request #235
Opened 2021-01-18 19:20 UTC by st--

Addresses #233

2021-01-19 11:18 UTC, devmotion requested changes
Looks good roughly but it seems you forgot to add the deprecations.

2021-01-19 11:25 UTC, st-- commented
> Looks good roughly but it seems you forgot to add the deprecations.

So I did! I added the _tests_ of the deprecation and apparently was so used to writing code first I then didn't think anymore about actually deprecating them. Thanks for pointing that out :laughing:

2021-01-19 11:47 UTC, devmotion commented on src/deprecated.jl
> +end
`@deprecate` expects a different format. Also the deprecations are not correct and will error since the vector-based methods (the default) do not take any keyword arguments.
```suggestion
@deprecate kerneldiagmatrix(k::Kernel, x::AbstractVector) kernelmatrix_diag(k, x)
@deprecate kerneldiagmatrix(k::Kernel, x::AbstractVector, y::AbstractVector) kernelmatrix_diag(k, x, y)
@deprecate kerneldiagmatrix!(out::AbstractVector, k::Kernel, x::AbstractVector) kernelmatrix_diag!(out, k, x)
@deprecate kerneldiagmatrix!(out::AbstractVector, k::Kernel, x::AbstractVector, y::AbstractVector) kernelmatrix_diag!(out, k, x, y)

@deprecate kerneldiagmatrix(k::Kernel, X::AbstractMatrix; obsdim::Int=defaultobs) kernelmatrix_diag(k, X; obsdim=obsdim)
@deprecate kerneldiagmatrix(k::Kernel, X::AbstractMatrix, Y::AbstractMatrix; obsdim::Int=defaultobs) kernelmatrix_diag(k, X, Y; obsdim=obsdim)
@deprecate kerneldiagmatrix!(out::AbstractVector, k::Kernel, X::AbstractMatrix; obsdim::Int=defaultobs) kernelmatrix_diag!(out, k, X; obsdim=obsdim)
@deprecate kerneldiagmatrix!(out::AbstractVector, k::Kernel, X::AbstractMatrix, Y::AbstractMatrix; obsdim::Int=defaultobs) kernelmatrix_diag!(out, k, X, Y; obsdim=obsdim)
```

2021-01-19 11:59 UTC, devmotion requested changes
The deprecations are not correct, please see my comments.

2021-01-19 11:59 UTC, devmotion commented on src/deprecated.jl
> +)
As mentioned earlier, this is not correct. Instead you have to use:
```suggestion
@deprecate kerneldiagmatrix(k::Kernel, x::AbstractVector) kernelmatrix_diag(k, x)
@deprecate kerneldiagmatrix(k::Kernel, x::AbstractVector, Y::AbstractVector) kernelmatrix_diag(k, x, y)
@deprecate kerneldiagmatrix!(out::AbstractVector, k::Kernel, x::AbstractVector) kernelmatrix_diag!(out, k, x)
@deprecate kerneldiagmatrix!(out::AbstractVector, k::Kernel, x::AbstractVector, y::AbstractVector) kernelmatrix_diag!(out, k, x, y)

@deprecate kerneldiagmatrix(k::Kernel, X::AbstractMatrix; obsdim::Int=defaultobs) kernelmatrix_diag(
    k, X; obsdim=obsdim
)
@deprecate kerneldiagmatrix(k::Kernel, X::AbstractMatrix, Y::AbstractMatrix; obsdim::Int=defaultobs) kernelmatrix_diag(
    k, X, Y; obsdim=obsdim
)
@deprecate kerneldiagmatrix!(out::AbstractVector, k::Kernel, X::AbstractMatrix; obsdim::Int=defaultobs) kernelmatrix_diag!(
    out, k, X; obsdim=obsdim
)
@deprecate kerneldiagmatrix!(out::AbstractVector, k::Kernel, X::AbstractMatrix, Y::AbstractMatrix; obsdim::Int=defaultobs) kernelmatrix_diag!(
    out, k, X, Y; obsdim=obsdim
)
```

2021-01-27 08:51 UTC, devmotion requested changes

2021-01-27 08:51 UTC, devmotion commented on test/matrix/kernelmatrix.jl
> +            @test tmp_diag_dep ≈ kernelmatrix_diag(k, x)
Can we test all deprecations? I.e., one + two inputs, vectors (i.e. ColVecs or RowVecs), and matrices without and with different `obsdim`?

2021-01-27 09:55 UTC, st-- commented on test/matrix/kernelmatrix.jl
> +            @test tmp_diag_dep ≈ kernelmatrix_diag(k, x)
We can do that of course! Could you give me a bit more insight into your motivation for that - what's the value of extensive tests of code-to-be-removed? I know the value of tests for code that's changed or new code, just here it seems more effort than worth it to me, so I'm wondering what I might be missing!

2021-01-27 09:56 UTC, devmotion commented on test/matrix/kernelmatrix.jl
> +            @test tmp_diag_dep ≈ kernelmatrix_diag(k, x)
If we don't test it, the deprecations might be incorrect, which in turn breaks existing code.

2021-01-27 11:09 UTC, st-- commented on test/matrix/kernelmatrix.jl
> +            @test tmp_diag_dep ≈ kernelmatrix_diag(k, x)
Ok... in this case getting the deprecation test right (and making sure they're all covered) seems more effort than checking the deprecations (manually in deprecated.jl) as it's purely a rename. Is there some way of testing for un-tested deprecations? The coverage report seems to entirely ignore deprecated.jl.

2021-01-27 11:22 UTC, st-- commented
I noticed that the in-place kernelmatrix[_diag]! forms only tested the return value, not whether it correctly got written to the passed-in array, so I've added those as well

2021-01-27 11:32 UTC, devmotion commented
Oh, good that you added these other tests as well!

> The tests of utils.jl and pairwise.jl in contrast only test the passed-in array and don't check the return value, should we add those as well?

Probably, but in my opinion it should be done in a separate PR.

2021-01-27 11:32 UTC, devmotion approved these changes
Thanks, looks good!

Can you bump the version? Then it can be merged and released, if tests pass.

2021-01-27 12:12 UTC, devmotion commented on src/matrix/kernelmatrix.jl
>      return map!(κ, x, y)
```suggestion
    return map!(κ, K, x, y)
```

2021-01-27 12:17 UTC, devmotion commented on test/matrix/kernelmatrix.jl
> +            @test_deprecated kerneldiagmatrix!(tmp_diag_dep, k, x, x)
It would be cleaner/safer to reset `tmp_diag_dep`. Otherwise the test of the return value might pass even if the function is implemented incorrectly:

```suggestion

            tmp_diag_dep = Vector{Float64}(undef, length(x))            
            @test_deprecated kerneldiagmatrix!(tmp_diag_dep, k, x, x)
```

BTW it seems we only test `kernelmatrix_diag!(out, k, x)` but not `kernelmatrix_diag!(out, k, x, y)` above in the non-deprecated section?

2021-01-27 12:19 UTC, devmotion commented on test/matrix/kernelmatrix.jl
> +            @test tmp_diag_dep == kernelmatrix_diag(k, X, X; obsdim=obsdim)
Same here, it would be better to reset `tmp_diag_dep` and `kernelmatrix_diag!(out, k, X, Y; obsdim)` seems to be missing in the non-deprecated tests.

2021-01-27 13:04 UTC, st-- commented on src/matrix/kernelmatrix.jl
>      return map!(κ, x, y)
Ah, thanks for spotting that, I was just trying to look through why the tests were failing before. Turns out my added tests for in-place array actually uncovered a bug in the preexisting code :grin:

2021-01-27 13:06 UTC, st-- commented on test/matrix/kernelmatrix.jl
> +            @test_deprecated kerneldiagmatrix!(tmp_diag_dep, k, x, x)
I'll add that as well - though I was already wondering about what the use-case for kernelmatrix_diag(k, x, y) is! it seems like code that needs maintaining without any benefit I can see from it - what would you use it for?

2021-01-27 13:07 UTC, st-- commented on test/matrix/kernelmatrix.jl
> +            @test tmp_diag ≈ kernelmatrix_diag(k, x)
```suggestion
            @test tmp_diag ≈ kernelmatrix_diag(k, x)
            tmp_diag = Vector{Float64}(undef, length(x))
            @test kernelmatrix_diag!(tmp_diag, k, x, x) ≈ kernelmatrix_diag(k, x, x)
            @test tmp_diag ≈ kernelmatrix_diag(k, x, x)
```

2021-01-27 13:10 UTC, st-- commented on test/matrix/kernelmatrix.jl
> +            @test kernelmatrix_diag(k, x) ≈ tmp_diag
```suggestion
            @test kernelmatrix_diag(k, x) ≈ tmp_diag
            tmp_diag = Vector{Float64}(undef, length(x))
            @test kernelmatrix_diag!(tmp_diag, k, X, X; obsdim=obsdim) ≈
                  kernelmatrix_diag(k, x, x)
            @test tmp_diag ≈ kernelmatrix_diag(k, x, x)
```

2021-01-27 13:10 UTC, st-- commented on test/matrix/kernelmatrix.jl
> +            @test_deprecated kerneldiagmatrix!(tmp_diag_dep, k, X, X; obsdim=obsdim)
```suggestion
            tmp_diag_dep = Vector{Float64}(undef, length(x))
            @test_deprecated kerneldiagmatrix!(tmp_diag_dep, k, X, X; obsdim=obsdim)
```

2021-01-27 13:12 UTC, st-- commented
While we're looking at this: what's the use-case for kernelmatrix_diag(k, x, y) (with x != y but same shape)? I can't think of any place I'd actually use that code, so is it worth incurring the maintenance cost (like we've had now)? What for or where would you use it?

2021-01-27 13:37 UTC, devmotion commented
I haven't used `kerneldiagmat` in any downstream code but I would have assumed that the two argument version is more useful. For e.g. translation-invariant kernels `kerneldiagmat(k, x)` is just trivial and returns a constant vector (usually of ones for unscaled kernels) whereas `kerneldiagmat(k, x, y) = [k(xi, yi) for (xi, yi) in zip(x, y)]` is a more interesting non-constant vector.

2021-01-27 14:12 UTC, st-- commented
> I haven't used `kerneldiagmat` in any downstream code but I would have assumed that the two argument version is more useful. For e.g. translation-invariant kernels `kerneldiagmat(k, x)` is just trivial and returns a constant vector (usually of ones for unscaled kernels) whereas `kerneldiagmat(k, x, y) = [k(xi, yi) for (xi, yi) in zip(x, y)]` is a more interesting non-constant vector.

In Gaussian process models it's exactly the `kernelmatrix_diag(k, x)` that's needed - it may be trivial for stationary kernels (but also has the advantage it's super fast to compute), but it's also common to use non-stationary kernels (e.g. linear, arc-cosine, change-points). I've not come across a use-case for `kernelmatrix_diag(k, x, y)` with y!=x which is why I asked. If we can't think of any use-cases, would it not be better to save the maintenance cost? What's the value of keeping around functions just because we can write them if we have no use for it?

2021-01-27 14:15 UTC, st-- commented
The one failing CI run seems to be some blip (if anyone can explain why that would happen intermittently, I'd be curious to find out). So I'm going to go ahead and merge it as is. I've moved the open question to a separate issue (#250).

2021-01-27 14:17 UTC, merged

2021-01-27 14:18 UTC, theogf commented
> While we're looking at this: what's the use-case for kernelmatrix_diag(k, x, y) (with x != y but same shape)? I can't think of any place I'd actually use that code, so is it worth incurring the maintenance cost (like we've had now)? What for or where would you use it?

@willtebbutt motivated this as he needs it for Stheno

2021-01-27 14:20 UTC, st-- commented
I've bumped the version. Is there anything else that needs doing to release?

@willtebbutt can you point me to the concrete use? would be curious to understand what you do with it.

2021-01-27 14:22 UTC, theogf commented
> I've bumped the version. Is there anything else that needs doing to release?

Yes, I just did. You can check it out all you need is to write a comment to the merging commit with `@JuliaRegistrator register`

2021-01-27 14:22 UTC, JuliaRegistrator commented
Comments on pull requests will not trigger Registrator, as it is disabled. Please try commenting on a commit or issue.

2021-01-27 14:22 UTC, JuliaRegistrator commented
Comments on pull requests will not trigger Registrator, as it is disabled. Please try commenting on a commit or issue.

2021-01-27 14:29 UTC, st-- commented
Ah, neat. The docs suggest that given TagBot is installed in this repo's workflow it should automatically add a tag for the new release. How long does it usually take for that to happen? I can't see a new tag yet..

2021-01-27 14:32 UTC, theogf commented
So first it needs to be registered in the Registry and that takes around 20 min (there is a cycle of automerge every 15 min or so) and then TagBot will automatically create a new tag with closes issues / pull request merged, that we can then edit