Use only docstrings in documentation + fix them
JuliaGaussianProcesses/KernelFunctions.jl pull request #236
Opened 2021-01-19 02:16 UTC by devmotion

Addresses https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/218 and https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/216 and uses the docstrings in the documentation of kernel functions and transformation.

The docstrings are updated and synced with the documentation, a bunch of errors are fixed (e.g., incorrect Matérn kernel functions and rational quadratic kernels), formatting of most docstrings of kernels and transformations is fixed (basically everything apart from the Wiener kernel and spectral mixture kernel, I was too tired to fix the mess there), doctests are added to most transformations, and incorrect explanations and outdated code of the transformations are fixed.

2021-01-19 02:16 UTC, devmotion commented on docs/src/kernels.md
>  ## Rational Quadratic
```suggestion
## Rational Quadratic Kernels
```

2021-01-19 10:24 UTC, devmotion commented on src/basekernels/exponential.jl
> +        @check_args(GammaExponentialKernel, γ, zero(γ) < γ ≤ 2, "γ ∈ (0, 2]")
Otherwise the kernel is not positive definite (the case 0 is not interesting and was excluded in the docstring but not in the check itself).

2021-01-19 10:25 UTC, devmotion commented on src/basekernels/fbm.jl
> +        @check_args(FBMKernel, h, zero(h) ≤ h ≤ one(h), "h ∈ [0, 1]")
Also here `h=0` is uninteresting.

2021-01-19 10:27 UTC, devmotion commented on src/basekernels/matern.jl
> +k(x, x') = \\big(1 + \\sqrt{3} \\|x - x'\\|_2 \\big) \\exp\\big(- \\sqrt{3}\\|x - x'\\|_2\\big).
The current documentation is incorrect, it is missing the minus sign inside the exponential.

2021-01-19 10:28 UTC, devmotion commented on src/basekernels/matern.jl
> +           \\exp\\big(- \\sqrt{5}\\|x - x'\\|_2\\big).
Same here, the current docs are missing the minus sign.

2021-01-19 10:33 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +k(x, x'; \\alpha) = \\bigg(1 + \\frac{\\|x - x'\\|_2^2}{2\\alpha}\\bigg)^{-\\alpha}.
Currently, docstring and documentation are not consistent - the documentation is missing a factor of 2 in the denominator. Since the docstring and code were consistent, I only fixed the format of the docstring. IIRC you changed this a while back @willtebbutt?

2021-01-19 10:46 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +k(x, x'; \\alpha, \\gamma) = \\bigg(1 + \\frac{\\|x - x'\\|_2^{\\gamma}}{2\\alpha}\\bigg)^{-\\alpha}.
Also here's an inconsistency between docstring and documentation currently - the documentation includes an additional factor of 2 in the exponent. Since `RationalQuadraticKernel` and `GammaRationalQuadraticKernel` are grouped together in the documentation and refer to each other in the docstring, I noticed an inconsistency in the implementation: `RationalQuadraticKernel` includes an additional factor of 2 in the denominator whereas `GammaRationalQuadraticKernel` doesn't. Is there a reason for this behaviour or is this a bug, @willtebbutt?

With the additional factor of 2 in the denominator, the more general kernel would yield the same kernel with its default values whereas currently the inputs have to be scaled. On the other hand, one would lose the property that the `GammaExponentialKernel` is the limit of the `GammaRationalQuadraticKernel` as alpha goes to infinity. But the name "GammaRationalQuadraticKernel" seems to indicate that it is more closely related to the `RationalQuadraticKernel`...

Maybe
- one should rename `GammaRationalQuadraticKernel` to `GammaRationalKernel` now that the factor 2 in the exponent is removed
- add an explicit `RationalKernel` for the case `gamma=1` of the `GammaRationalQuadraticKernel`, which yields an `ExponentialKernel` as alpha goes to infinity
- change the default value of gamma of the `GammaRationalKernel` to 1, such that it is a generalization of `RationalKernel` instead of `RationalQuadraticKernel`, similar to the relation of `ExponentialKernel` and `GammaExponentialKernel`

Then everything would be consistent with the setup in the limit for alpha=\infty.

What do you think, @willtebbutt?

2021-01-19 10:47 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +    return (one(d) + d^first(κ.γ) / (2 * first(κ.α)))^(-first(κ.α))
Is there a reason for using the `SqEuclidean` distance and dividing gamma by 2 instead of this approach? (For a discussion of the 2 here, see above)

2021-01-19 11:12 UTC, devmotion commented on test/basekernels/exponential.jl
> +        test_ADs(γ -> GammaExponentialKernel(; gamma=first(γ)), [1 + 0.5 * rand()])
Ideally, one should use a reparameterization `R -> (0,2]` here, e.g. `f(x) = 2 * logistic`. With the current boundary point `gamma = 2` finite differencing errors.

2021-01-19 11:15 UTC, devmotion commented on src/basekernels/rationalquad.jl
> +k(x, x'; \\alpha, \\gamma) = \\bigg(1 + \\frac{\\|x - x'\\|_2^{\\gamma}}{2\\alpha}\\bigg)^{-\\alpha}.
I kept the current definition for now since these changes should not be part of the PR.

2021-01-19 12:53 UTC, willtebbutt requested changes
This is really fantastic work. Just a few things to fix.

2021-01-19 12:53 UTC, willtebbutt commented on docs/src/transform.md
> +[`Transform`](@ref) is the object that takes care of transforming the input data before distances are being computed.
```suggestion
[`Transform`](@ref)s are designed to change input data before passing it on to a kernel object.
```

2021-01-19 12:53 UTC, willtebbutt commented on docs/src/transform.md
> +
I think we should at least mention the `transform` function and `TransformedKernel` type in this function, so as to explain to users how to actually _use_ transforms.

2021-01-19 12:53 UTC, willtebbutt commented on docs/src/kernels.md
Could you add a sentence or two here explaining what we mean by `Composite Kernels` and why we have them etc?

2021-01-19 12:53 UTC, willtebbutt commented on src/kernels/scaledkernel.jl
> +    ScaledKernel(k::Kernel, σ²::Real=1.0)
There's an inconsistency here between the name of the argument `k`, and what its called in the definition below: ``\\widetilde{k}``. Could you maybe swap some of the names around? Perhaps ``\\widetilde{k}`` should be the derived kernel?

2021-01-19 12:53 UTC, willtebbutt commented on src/kernels/transformedkernel.jl
> +# Definition
Could you add a note suggesting that users should prefer to use `transform`, rather than `TransformedKernel` directly?

2021-01-19 12:53 UTC, willtebbutt commented on src/kernels/transformedkernel.jl
> +    TransformedKernel(k::Kernel, t::Transform)
Same here regarding the inconsistency between the name in the signature and the name in the maths.

2021-01-19 13:12 UTC, devmotion commented on src/kernels/transformedkernel.jl
> +For inputs ``x, x'``, the transformed kernel derived from kernel ``\\widetilde{k}`` by
```suggestion
For inputs ``x, x'``, the transformed kernel ``\\widetilde{k}`` derived from kernel ``k`` by
```

2021-01-19 13:13 UTC, devmotion commented on src/kernels/transformedkernel.jl
> +k(x, x'; t, \\widetilde{k}) = \\widetilde{k}(t(x), t(x')).
```suggestion
\\widetilde{k}(x, x'; k, t) = k\\big(t(x), t(x')\\big).
```

2021-01-19 13:17 UTC, devmotion commented on src/kernels/transformedkernel.jl
> +
```suggestion

It is preferred to use [`transform`](@ref) instead of constructing `TransformedKernel`
directly.

```

2021-01-19 13:19 UTC, devmotion commented on src/kernels/scaledkernel.jl
> +k(x, x'; \\sigma^2, \\widetilde{k}) = \\sigma^2 \\widetilde{k}(x, x').
```suggestion
For inputs ``x, x'``, the scaled kernel ``\\widetilde{k}`` derived from kernel ``k`` by
multiplication with variance ``\\sigma^2 > 0`` is defined as
```math
\\widetilde{k}(x, x'; k, \\sigma^2) = \\sigma^2 k(x, x').
```

2021-01-19 14:24 UTC, devmotion commented on docs/src/kernels.md
> +```@docs
```suggestion
The modular design of KernelFunctions.jl uses [base kernels](@ref) as building blocks for
more complex kernels. These composite kernels can be created by adding
[input transforms](@ref) such as scaling the inputs with an inverse lengthscale, by scaling the
variance of a kernel, or by summing or multiplying different kernels.

```@docs
```

2021-01-19 14:47 UTC, devmotion commented on docs/src/transform.md
> +A transformation `t` can be applied to a vector `v` with `map`.
```suggestion

A transformation `t` can be applied to a single input `x` with `t(x)` and to multiple inputs
`xs` with `map(t, xs)`.

Kernels can be coupled with input transformations with
[`transform`](@ref). It falls back to creating a [`TransformedKernel`](@ref) but allows more
optimized implementations for specific kernels and transformations.
```

2021-01-19 16:10 UTC, devmotion commented on docs/src/transform.md
> +
I added some additional sentences about `transform` and `TransformedKernel`.

2021-01-19 16:10 UTC, devmotion commented on docs/src/kernels.md
I added a short paragraph for now.

2021-01-19 16:11 UTC, devmotion commented on src/kernels/scaledkernel.jl
> +    ScaledKernel(k::Kernel, σ²::Real=1.0)
I swapped it in the mathematical notation.

2021-01-19 16:11 UTC, devmotion commented on src/kernels/transformedkernel.jl
> +# Definition
I added a short statement.

2021-01-19 16:11 UTC, devmotion commented on src/kernels/transformedkernel.jl
> +    TransformedKernel(k::Kernel, t::Transform)
I changed it.

2021-01-19 16:20 UTC, willtebbutt commented on docs/src/kernels.md
This is good, but as currently phrased it sounds like this list is somewhat final, and unlikely to be extended. I think it would be better to phrase it in a manner that suggests that we've got a variety of things implemented, but you can always add more. Perhaps something like:

```
There are a variety of composite kernels implemented, including those which
[transform the inputs](@ref input_transforms) to a wrapped kernel to implement length scales, scale the variance of a kernel, and sum or multiply collections of kernels together.
```

Something like that perhaps?

2021-01-19 16:24 UTC, devmotion commented on docs/src/kernels.md
Sure, sounds good :+1: I was not very creative and did not think too much about the wording. I'll update it according to your suggestions!

2021-01-19 16:31 UTC, willtebbutt approved these changes
Thanks for addressing my points. Now LGTM.

2021-01-19 18:27 UTC, merged

2021-01-20 11:22 UTC, st-- commented
The downside of this is that while the maths may look nice on the rendered docs online, the REPL help is now rather less helpful compared to the previous use of unicode maths in the docstrings, e.g.:
```
  MaternKernel(; ν::Real=1.5)

  Matérn kernel of order ν.

  Definition
  ≡≡≡≡≡≡≡≡≡≡≡≡

  For inputs x, x' \in \mathbb{R}^d, the Matérn kernel of order \nu > 0 is defined as

  k(x,x';\nu) = \frac{2^{1-\nu}}{\Gamma(\nu)}\big(\sqrt{2\nu}\|x-x'\|_2\big) K_\nu\big(\sqrt{2\nu}\|x-x'\|_2\big),

  where \Gamma is the Gamma function and K_{\nu} is the modified Bessel function of the second kind of order \nu.

  A Gaussian process with a Matérn kernel is \lceil \nu \rceil - 1-times differentiable in the mean-square sense.
```
How about keeping the unification (:+1:) but using unicode for maths as in the docstrings before?

2021-01-20 11:33 UTC, devmotion commented
I tried this recently in some other package but unfortunately unicode math does not work reliably with Documenter (or the javascript libraries). Greek letters are displayed in a different non-math font, brackets can not be adjusted properly, unicode supports only a limited number of sub- and superscripts etc. Other things such as `\frac` are just not possible to write with unicode characters only. So in any case one would end up with a mix of both LaTeX and unicode characters, which makes e.g. the differences of the fonts even more prominent and does not solve the problem of LaTeX syntax in docstrings.

2021-01-20 11:38 UTC, devmotion commented
Possibly also due to these reasons, LaTeX syntax in docstrings is common practice in other packages such as Distributions (see e.g. https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/discrete/betabinomial.jl) and standard libraries (see e.g. https://github.com/JuliaLang/julia/blob/d6f99481b1d5cf399165be2eb3893c5bdbe90dcf/stdlib/LinearAlgebra/src/qr.jl#L19)

2021-01-20 13:04 UTC, theogf commented
I chime in definitely too late, but that was the reason for two versions of the docs (docstring vs docs.md), unicode readable for docstring and latex for documenter.

2021-01-20 13:59 UTC, devmotion commented
I definitely agree that it would be nice to have some more readable output in the REPL and I tried to use unicode but it does not work. Only the simplest formulas can be written with unicode only, so one basically always has to write them at least partly with LaTeX syntax. And even the simplest unicode formulas look terrible on the webpage (e.g. even subscripts and operators such as `exp`).

2021-01-20 14:03 UTC, devmotion commented
On a different note, it might also be problematic if the docstring contains characters that are only supported by very few fonts.