Add NormalizedKernel
JuliaGaussianProcesses/KernelFunctions.jl pull request #274
Opened 2021-04-07 19:17 UTC by rossviljoen

This PR adds a composite kernel to normalize a kernel as follows:

`k'(x, y) = k(x, y) / sqrt(k(x, x), k(y, y))`

As discussed in #259.

2021-04-07 19:47 UTC, devmotion requested changes

2021-04-07 19:47 UTC, devmotion commented on src/kernels/normalizedkernel.jl
> +
```suggestion
```

2021-04-07 19:47 UTC, devmotion commented on src/kernels/normalizedkernel.jl
> +    return kernelmatrix(κ.kernel, x, y) ./ _normalizationmatrix(κ, x, y)
The separate functions `_normalizationmatrix` and `_normalizationmatrix_diag` cause additional allocations since the broadcasting operations are not fused anymore.

2021-04-07 19:47 UTC, devmotion commented on src/kernels/normalizedkernel.jl
> +Base.show(io::IO, κ::NormalizedKernel) = printshifted(io, κ, 0)
Isn't this the default fallback?

2021-04-07 19:47 UTC, devmotion commented on src/kernels/normalizedkernel.jl
> +    print(io, "Normalized Kernel:" * "\n")
```suggestion
    println(io, "Normalized Kernel:")
```

2021-04-07 19:49 UTC, devmotion commented
Thanks for your PR! It looks very good :+1: I left some comments, mostly I am worried about the additional allocations. Could we try to make sure that broadcasting operations are fused as much as possible?

2021-04-09 17:04 UTC, rossviljoen commented on src/kernels/normalizedkernel.jl
> +Base.show(io::IO, κ::NormalizedKernel) = printshifted(io, κ, 0)
It looks like the default is just plain print, so I think this should stay?

2021-04-09 17:07 UTC, devmotion commented on src/kernels/normalizedkernel.jl
> +Base.show(io::IO, κ::NormalizedKernel) = printshifted(io, κ, 0)
Yes, you're right, I remembered it incorrectly :+1:

2021-04-09 18:33 UTC, rossviljoen commented
Thanks for the comments! I think I fused the broadcasts as much as possible?

I also optimised the `kernelmatrix_diag` functions to just return the one vector, but is there a better way to get the right return shape/type of the inner kernel than something like `map(one, kernelmatrix_diag(κ.kernel, x))`?

2021-04-09 21:10 UTC, devmotion commented
Hm, in general it is not guaranteed that `map(one, ...)` returns a vector with the same element type as `kernelmatrix_diag(κ, x, x)`, e.g., if the kernel does not return floating point numbers. So it is a bit unsatisfying even if probably such a situation is quite rare. Maybe it would be better (and more efficient, I think) to define
```julia
function kernelmatrix_diag(κ::NormalizedKernel, x::AbstractVector)
    first_x = first(x)
    return Fill(κ.kernel(first_x, first_x), length(x))
end
```
Then the number type of `kernelmatrix_diag(κ, x)` and `kernelmatrix_diag(κ, x, x)` would be the same, it seems, and it would not even allocate a full vector. However, of course, this would imply that the exact types of `kernelmatrix_diag(κ, x)` and `kernelmatrix_diag(κ, x, x)` would still be different.

2021-04-10 17:47 UTC, devmotion commented on src/kernels/normalizedkernel.jl
> +    return fill(κ(first_x, first_x), length(x))
Have you tried to use
```suggestion
    return Fill(κ(first_x, first_x), length(x))
```
with `Fill` from FillArrays? It should behave like `fill` but does not actually allocate an array.

2021-04-10 19:23 UTC, devmotion approved these changes
Looks good to me if tests pass. Thank you for this great PR! Can you update the version number in Project.toml to 0.9.2 so we can make a new release once the PR is merged?

2021-04-10 20:04 UTC, rossviljoen commented
Thank you!

There is a failing test for the Zygote gradient of `kernelmatrix_diag`, seemingly because:

```
julia> A = [1 2; 3 4]
julia> Zygote.gradient(x -> sum(kernelmatrix_diag(NormalizedKernel(SqExponentialKernel()), x)), A)

ERROR: MethodError: no method matching (::KernelFunctions.var"#ColVecs_pullback#175")(::Vector{Union{Nothing, Vector{Float64}}})
```

I'm not that familiar with Zygote, so I'm not sure if the problem is with `ColVecs_pullback` or elsewhere?
Incidentally, the gradient for a vector is fine:
```
julia> B = [1, 2]
julia> Zygote.gradient(x -> sum(kernelmatrix_diag(NormalizedKernel(SqExponentialKernel()), x)), B)
([0.0, 0.0],)
```

2021-04-10 20:07 UTC, theogf commented
Hey! kernelmatrix_diag expert here! I think the issue might from using broadcast over each sample. Typically using broadcast over ColVecs or RowVecs lead to problems with Zygote...

2021-04-10 20:09 UTC, theogf commented
Also we did not have the FillArrays dependency before, there is no way to do without it?

2021-04-10 20:10 UTC, devmotion commented
Does it work with `fill` instead of `Fill`?

2021-04-10 20:12 UTC, rossviljoen commented
The gradient doesn't work with `fill` either, no.

2021-04-10 20:16 UTC, devmotion commented
> Also we did not have the FillArrays dependency before, there is no way to do without it? 

It seemed fine to me since it only depends on standard libraries and is used by many packages in the ecosystem (such as AbstractGPs 😉). In principle, it should be more efficient to use `Fill` instead of `fill`, I was just worried if it breaks AD but it doesn't seem to be the case.

2021-04-10 20:19 UTC, theogf commented on src/kernels/normalizedkernel.jl
> +    return Fill(κ(first_x, first_x), length(x))
Can't we replace `Fill` by `Ones` here?
```suggestion
    return Ones{typeof(κ(first_x, first_x))},(length(x))
```

2021-04-10 20:21 UTC, theogf commented on src/kernels/normalizedkernel.jl
> +    return Fill(κ(first_x, first_x), length(x))
Or can some kernel return a negative value...

2021-04-10 20:24 UTC, theogf commented on src/kernels/normalizedkernel.jl
> +           sqrt.(
Isn't it generally more efficient to ocmpute the `sqrt` first? This is probably a performance detail though (and I don't know about machine accuracy)

2021-04-10 20:41 UTC, rossviljoen commented on src/kernels/normalizedkernel.jl
> +    return Fill(κ(first_x, first_x), length(x))
Look like this fixes the AD, cheers :)

2021-04-12 10:22 UTC, rossviljoen commented on src/kernels/normalizedkernel.jl
> +           sqrt.(
Doesn't this all get fused anyway though?

2021-04-12 10:24 UTC, rossviljoen commented on src/kernels/normalizedkernel.jl
> +    return Fill(κ(first_x, first_x), length(x))
I suppose k(x, x) could be zero as well?

2021-04-12 10:35 UTC, theogf commented on src/kernels/normalizedkernel.jl
> +    return Fill(κ(first_x, first_x), length(x))
But then we're in trouble cause we would be dividing by 0 and you would probably have bigger problems generally.

2021-04-15 09:19 UTC, devmotion commented
Are you satisfied with the PR @theogf? To me it seems it could be merged after updating the version number again (version 0.9.2 already exists) and adding a compatibility bound for FillArrays.

2021-04-15 09:37 UTC, theogf commented
Sure LGTM!

2021-04-15 09:37 UTC, theogf approved these changes

2021-04-15 12:25 UTC, merged

2021-04-15 12:40 UTC, devmotion commented
Thank you @rossviljoen!