Added vcat for ColVecs/RowVecs
JuliaGaussianProcesses/KernelFunctions.jl pull request #291
Opened 2021-05-30 12:23 UTC by kaandocal

Tentative fix for [this issue](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/issues/155) in AbstractGPs.

2021-05-30 12:31 UTC, devmotion requested changes

2021-05-30 12:31 UTC, devmotion commented on src/utils.jl
> +Base.vcat(a::ColVecs, b::ColVecs) = ColVecs(vcat(a.X, b.X))
I guess this should be
```suggestion
Base.vcat(a::ColVecs, b::ColVecs) = ColVecs(hcat(a.X, b.X))
```

2021-05-30 12:31 UTC, devmotion commented on src/utils.jl
> +Base.vcat(a::ColVecs, b::AbstractMatrix) = ColVecs(vcat(a.X, b))
This is not well defined, I'd suggest to remove it:
```suggestion
```

2021-05-30 12:31 UTC, devmotion commented
Can you also add some tests?

2021-05-30 12:33 UTC, kaandocal commented on src/utils.jl
> +Base.vcat(a::ColVecs, b::AbstractMatrix) = ColVecs(vcat(a.X, b))
I thought it could be useful but you're right.

2021-05-31 11:42 UTC, willtebbutt approved these changes
LGTM. Just requires a patch version bump then we're good to go provided that @devmotion is happy.

2021-05-31 12:30 UTC, devmotion reviewed
I think the tests could be improved a bit and actually check that we do the correct thing, e.g., by concatenating two different objects and checking that the concatenated values are correct (I also don't think that the check `typeof(DX) == typeof(vcat(DX, DX))` is important - it's not the main purpose of the implementation and only a by-product if one actually concatenates two `RowVecs` or `ColVecs` whose underlying matrices have the same type). Otherwise, only the version bump seems to be missing :slightly_smiling_face:

2021-06-03 11:45 UTC, kaandocal commented
@devmotion I've modified the tests to what you suggested - nothing extensive, but given the simplicity of the PR I wasn't at my most creative. Let me know if you have other suggestions!

2021-06-03 11:49 UTC, devmotion commented on test/utils.jl
> +        @test vcat(DX, DY) == ColVecs(hcat(X, Y))
A small suggestion since `ColVecs(X) == collect(eachcol(X))` is `true` as well:
```suggestion
        @test vcat(DX, DY) isa ColVecs
        @test vcat(DX, DY).X == hcat(X, Y)
```

2021-06-03 11:49 UTC, devmotion commented on test/utils.jl
> +        @test vcat(DX, DY) == RowVecs(vcat(X, Y))
```suggestion
        @test vcat(DX, DY) isa RowVecs
        @test vcat(DX, DY).X == vcat(X, Y)
```

2021-06-03 11:58 UTC, devmotion approved these changes

2021-06-03 12:10 UTC, willtebbutt approved these changes

2021-06-03 12:58 UTC, merged

2021-06-03 12:58 UTC, devmotion commented
Thanks a lot for the PR :+1: