Adding Gibbskernel
JuliaGaussianProcesses/KernelFunctions.jl pull request #374
Opened 2021-09-29 07:04 UTC by Cyberface

**Summary**

This PR begins to implement the non-stationary Gibbs kernel what is being discussed in issue: #372 

This is a modification of the standard Squared-Exponential kernel where the lengthscale is no longer constant but is a function of the input parameters.

In this PR I have simply added a function `GibbsKernel` to evaluate the gibbs kernel as well as added a test to check that when the lengthscale function just returns a constant value of `1.0` then it should be the same as the `SqExponentialKernel()`.

The implementation of the gibbs kernel is probably going to change as I learn more about how your kernels are defined/implemented.

This is my first PR here and I am only just starting to learn julia so I'm sorry for some basic mistakes!
And I appriciate any comments to make this better thanks!

**Proposed changes**

* Adds a new file "src/kernels/gibbskernel.jl"
* include and export this in "src/KernelFunctions.jl"
* add tests and include the test in "test/runtests.jl"

**What alternatives have you considered?**

A better implementation would be to use the kernel/transform infrastructure you have and I will work on this after this PR.

**Breaking changes**

None

2021-09-29 10:36 UTC, willtebbutt reviewed
Thanks for opening this! It's a very nice well-sized PR.

The basic functionality all seems is present. The main thing that needs addressing is turning the `GibbsKernel` `function` into a `struct` (see comment below) -- other than that it's just formatting-related things and other minor details that need addressing.

2021-09-29 10:36 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +end
```suggestion
struct GibbsKernel{T} <: Kernel
    ell::T
end

function (k::GibbsKernel)(x, y)
    fac = k.ell(x)^2 + k.ell(y)^2
    term1 = 2 * k.ell(x) * k.ell(y) / fac
    term2 = -(x-y)^2 / fac
    return term1 * exp(term2)
end
```
I think all of the functionality is here. The main change this suggestion makes is to create a `Kernel` called `GibbsKernel` and define a way to evaluate it. This is needed to ensure that the kernel behaves in the same way as our other kernels.

Minor changes -- these are new-to-Julia things that are more general than this PR:
1. remove `::Any` restrictions on `x` and `y`. `Any` is implicitly assumed if no type constraint is specified.
2. `2.0` -> `2`. This will generally interact better with Julia promotion mechanisms. For example, if `k.ell(x) * k.ell(y) / fac` is a `Float32` then probably what we want is for `term1` to be a `Float32`. Multiplying by `2.0` will produce a `Float64`, because `Float64 * Float32 -> Float64`, while multiplying by `2` will give a `Float32` as desired.

In the tests, you'll now be able to write things like
```julia
k_gibbs = GibbsKernel(ell)
k_gibbs(x, y)
```
etc.

2021-09-29 10:36 UTC, willtebbutt commented on test/kernels/gibbskernel.jl
> +
```suggestion
```
You'll get these in this file via the main `runtests.jl` file.

2021-09-29 10:36 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +
```suggestion
```
Don't think this empty line is needed.

2021-09-29 10:36 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +#function (k::GibbsKernel)(x, y, ell)
```suggestion
```
I think these lines need to go in order for Julia to understand that the docstring is for `GibbsKernel` -- currently, if you type `?GibbsKernel` at the REPL it doesn't produce the docstring.

2021-09-29 10:36 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +k(x, y) = \\sqrt{ \\left( \\frac{2 \\ell(x) \\ell(y)}{\\ell(x)^2 + \\ell(y)^2} \\right) } \\quad \\rm{exp} \\left( - \\frac{(x - y)^2}{\\ell(x)^2 + \\ell(y)^2} \\right)
Style: might it be possible to get this to under 92 characters by spreading it out on to 2 lines?

2021-09-29 10:45 UTC, theogf commented on src/kernels/gibbskernel.jl
> +end
Another small thing:
Assuming that `ell` could be expensive, it might worth precomputing them first and then using them.

2021-09-29 10:51 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +end
Agreed -- I think this should be done in a follow up PR as an optimisation for `kernelmatrix` etc.

2021-09-29 10:52 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +end
I think it would be good to allow to specify a distance measure, as in the case of `SqExponentialKernel`. Maybe one could (should?) also implement `(::GibbsKernel)(x, y)` by constructing a corresponding scaled `SqExponentialKernel` with the correct lengthscale and evaluate it to make use of the optimizations for lengthscales and certain distance measures. In any case, we should not use `(x - y)^2` since it will fail for non-scalar inputs.

2021-09-29 10:56 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +end
Agreed -- could we fix this in a follow-up PR though? Perhaps we just restrict the input types to `Real` in this PR?

2021-09-29 11:00 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +end
It would be a breaking change to add a new field for the distance measure (since it implies an additional type parameter and hence can break dispatches).

2021-09-29 11:05 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +end
Good point. Could you propose a suggestion that extends my one?

2021-09-29 12:29 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +end
Something like
```suggest
struct GibbsKernel{T,M} <: Kernel
    l::T
    metric::M
end

GibbsKernel(; l, metric=Euclidean()) = GibbsKernel(l, metric)

function (k::GibbsKernel)(x, y)
    l = k.l
    lx = l(x)
    ly = l(y)
    lengthscale = (lx^2 + ly^2) / 2
    kernel = (lx * ly / lengthscale) * with_lengthscale(SqExponentialKernel(k.metric), lengthscale)
    return kernel(x, y)
end
```
I think though we should use something more descriptive than `l` or `ell` though.

2021-09-29 12:31 UTC, theogf commented on src/kernels/gibbskernel.jl
> +end
I don't think that would be correct though!  The square applied on the `lengthscale` terms comes from the `SqEuclidean` norm. For different norms, I believe `lengthscale` would be different.

2021-09-29 12:39 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +end
Maybe, I did not study the original issue or the motivation for this particular choice 😄 It is always a squared exponential kernel though, just with a different metric, so the overall mathematical structure is the same. If necessary, we could make the computation of the variance and lengthscale also dependent on the metric.

2021-09-29 12:42 UTC, theogf commented on src/kernels/gibbskernel.jl
> +end
All I am saying it that we should probably not allow for other metrics than `SqEuclidean` for now.

2021-09-29 12:53 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +end
We use `Euclidean` as default. The squared metric, scaled with 1/2, is used and fixed in the definition of `SqExponentialKernel`. We always have a squared metric (which I referred to as same mathematical structure), and therefore I am less worried about the use of other metrics.

2021-09-29 13:02 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +end
Following on from Theo's point, a potential issue with using other metrics is that the Gibbs kernel is defined using some kind of integral against a white noise process (I forget the precise details), so it's possible that the right thing to do under metrics other than the Euclidean has some parametric form other than the one above.

2021-09-29 13:36 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +end
I'll read up on the details later today and check if it makes sense to allow to use a general metric. We could of course also just restrict the implementation to `(::GibbsKernel{<:Any,<:Euclidean})(x, y)` for now (this would avoid breaking changes in the future) or remove the `metric` field (if we think we don't want/need it and/or don't care about breaking changes).

In any case, my suggestion above was incorrect, it should be of course something like
```suggestion
struct GibbsKernel{T,M} <: Kernel
    l::T
    metric::M
end

GibbsKernel(; l, metric=Euclidean()) = GibbsKernel(l, metric)

function (k::GibbsKernel)(x, y)
    l = k.l
    lx = l(x)
    ly = l(y)
    lengthscale = hypot(lx, ly)
    kernel = (lx * ly / lengthscale^2) * with_lengthscale(SqExponentialKernel(k.metric), lengthscale)
    return kernel(x, y)
end
```

2021-09-29 16:11 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +end
> remove the metric field (if we think we don't want/need it and/or don't care about breaking changes).

Hmmm honestly I'm inclined to think that this is the case. If we need to make a breaking change at some point to support different metrics, so be it 🤷 .

I do agree that we ought to ensure that we either restrict the argument type to `Real`s, or generalise the implementation to vectors of reals. I'm inclined to think that former is better for the sake of getting this in quickly, so something like
```suggestion
struct GibbsKernel{T} <: Kernel
    ell::T
end

function (k::GibbsKernel)(x::Real, y::Real)
    fac = k.ell(x)^2 + k.ell(y)^2
    term1 = 2 * k.ell(x) * k.ell(y) / fac
    term2 = -(x-y)^2 / fac
    return term1 * exp(term2)
end
```

2021-09-29 16:25 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +end
I really think we shouls use `SqExponentialKernel` already in the first implementation since I think we want to use it at least in the vector case at some point - but then it would be another breaking change to switch to it since it uses a slightly different parameterization (factor 1/2 in the exponential).

I agree, probably it's easiest to not include the `metric` for now. Therefore I'd suggest, with a better name for `l`/`ell`:
```suggestion
struct GibbsKernel{T} <: Kernel
    l::T
end

GibbsKernel(; l) = GibbsKernel(l)

function (k::GibbsKernel)(x, y)
    l = k.l
    lx = l(x)
    ly = l(y)
    lengthscale = hypot(lx, ly)
    kernel = (sqrt(2 * lx * ly) / lengthscale) * with_lengthscale(SqExponentialKernel(), lengthscale)
    return kernel(x, y)
end
```
(BTW it seems `term1` is incorrect in all suggestions and the original implementation and does not correspond to the formula in the issue)

2021-09-29 16:42 UTC, Cyberface commented on src/kernels/gibbskernel.jl
> +k(x, y) = \\sqrt{ \\left( \\frac{2 \\ell(x) \\ell(y)}{\\ell(x)^2 + \\ell(y)^2} \\right) } \\quad \\rm{exp} \\left( - \\frac{(x - y)^2}{\\ell(x)^2 + \\ell(y)^2} \\right)
hopefully I have fixed this - I changed `ell` to `l`

2021-09-29 16:47 UTC, Cyberface commented on src/kernels/gibbskernel.jl
> +end
Thanks for such a lively discussion everyone!

@devmotion I just implemented your suggested and thanks for pointing out the error in `term1`!

I changed your `l` to `lengthscale` to hopefully make it obvious what it is and solve the `ell`/`l` issue.

I'm not entirely confident in my unit test either so will have to double check that too. I think it's because of the `1/2` in the `SqExponentialKernel` but I'll double check.

Nice idea about using the `with_lengthscale`.

2021-09-29 17:26 UTC, Cyberface commented
I have updated the unit test - it was a little more confusing and complicated that I originally thought! Hopefully you can follow what I've done through the comments.

Let me know what you think, cheers!

2021-09-30 08:39 UTC, Cyberface commented on test/kernels/gibbskernel.jl
> +    ell = randn(1)[1]
ah thanks! Implemented this in https://github.com/Cyberface/KernelFunctions.jl/commit/21de7d45d389f30012242f9c314f1faf1f7699f2

And ah I was doing `randn(1)` and didn't think to just do `randn()` very helpful thank you!

2021-09-30 08:42 UTC, Cyberface commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) == k(x, y)
I'm not really sure what you mean, could you elaborate or sketch out an idea of what you would like to see?

Thanks!

2021-09-30 08:57 UTC, theogf commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) == k(x, y)
Something like 
```
@test k_gibbs(x, y) == sqrt((ell(x) * ell(y)) / (ell(x)^2 + ell(y)^2)) * exp( - norm(x - y)^2 / (ell(x)^2 + ell(y)^2))
```

2021-09-30 08:58 UTC, theogf commented on test/kernels/gibbskernel.jl
> +    ell = randn(1)[1]
I think you just made a typo and wrote `ell = sum(sin, x)` instead of `ell(x) = sum(sin, x)`

2021-09-30 09:19 UTC, willtebbutt commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) == k(x, y)
n.b. probably better to use `≈` here rather than `==`.

2021-09-30 10:15 UTC, Cyberface commented on test/kernels/gibbskernel.jl
> +    ell = randn(1)[1]
I think it's correct, I wanted `ell` to just be a number and not a function right?

2021-09-30 10:15 UTC, Cyberface commented on test/kernels/gibbskernel.jl
> +    ell = randn(1)[1]
Oh I see what you mean in your other comment. This test is getting a bit confusing :)

2021-09-30 10:48 UTC, Cyberface commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) == k(x, y)
OK I see what you mean.  I've added your suggestion but actually this test is failing and I'm not sure why!

I don't think I fully understand the implementation in https://github.com/Cyberface/KernelFunctions.jl/blob/gibbskernel/src/kernels/gibbskernel.jl#L37 so will take a look a bit later again.

2021-09-30 11:42 UTC, theogf commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
```suggestion
    l = hypot(lx, ly) / sqrt(2)
    kernel = (sqrt(lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
```
I think this should more correspond to the exact formula

2021-09-30 11:46 UTC, theogf commented on test/kernels/gibbskernel.jl
> +    k_gibbs = GibbsKernel(l_func)
```suggestion
    # this is the gibbs lengthscale function.
    ell(x) = exp(sum(sin, 
    # create a gibbs kernel with our specific lengthscale function
    k_gibbs = GibbsKernel(ell)
```
That's more what I meant to use instead of a constant.

2021-09-30 12:10 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
Without promotion to Float64:
```suggestion
    l = invsqrt2 * hypot(lx, ly)
    kernel = (sqrt(lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
```

2021-09-30 12:51 UTC, Cyberface commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
Is this correct though because `l` is passed into `with_lengthscale` - doesn't the `SqExponentialKernel ` already have the `1/2` in the exponential looking [here](https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/master/src/basekernels/exponential.jl#L23)

2021-09-30 12:54 UTC, Cyberface commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) == k(x, y)
Are you sure the using `norm(x-y)` is correct here? Calling this on 

```
x = randn(2)
y = randn(2)
norm(x-y)
```
This returns a single number - shouldn't this be a 2x2 matrix?

Sorry for my confusion!

2021-09-30 13:25 UTC, Cyberface commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
shouldn't it be

```
l = hypot(lx, ly)
kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), 1 / l^2)
```

2021-09-30 13:29 UTC, theogf commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
> Is this correct though because l is passed into with_lengthscale - doesn't the SqExponentialKernel already have the 1/2 in the exponential looking here

Yes but in the latex formula the factor 2 is not there, so this way we cancel it out!

2021-09-30 13:30 UTC, theogf commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
@devmotion proposition is definitely the right one!

2021-09-30 13:30 UTC, Cyberface commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
oh yeh.... thanks!

2021-09-30 15:00 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
In general, the factor 2 in the exponential does not matter but it is a bit closer to the formulas in the issue 🤷‍♂️

2021-09-30 15:02 UTC, theogf commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
I guess the 2 disappears because we already have l(x) + l(y) ?

2021-09-30 15:03 UTC, theogf commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) == k(x, y)
No no, this the L2 norm! So it's `sqrt(sum((x_i - y_i)^2))`, this is what we would expect I think

2021-10-01 09:26 UTC, Cyberface commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
Yeah the 2 would be there when l(x) = l(y) = constant.

I think I finally understand most of the things here but I am confused by `with_lengthscale`. Can you explain why we shouldn't square the argument to with_lengthscale? Looking at the with_lengthscale code it seems to just multiply by `1/l`.

2021-10-01 09:27 UTC, Cyberface commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) == k(x, y)
OK I get you now - I thought this was supposed to give the covariance matrix but that is the `kernelmatrix` function!

This is just the covariance between two points in n-dimensions.

Hopefully I got this correct :)

2021-10-01 09:27 UTC, Cyberface commented
OK I think this PR is basically done?

2021-10-01 09:38 UTC, willtebbutt approved these changes
I'm happy -- once @theogf is happy, we can merge :)

2021-10-01 09:38 UTC, willtebbutt commented on src/kernels/gibbskernel.jl
> +
```suggestion
```
Needs to have no space between struct and docstring in order for the REPL and docs to pick up on it.

2021-10-01 09:48 UTC, theogf reviewed
Just a comment for the docstring. And could you also add the kernel in the docs (just add the kernel name in the list in docs/kernels.md)?

2021-10-01 09:48 UTC, theogf commented on src/kernels/gibbskernel.jl
> +``l(x) = l`` then you recover the standard Squared-Exponential kernel
```suggestion
For a constant function``l(x) = c``, one recovers the standard Squared-Exponential kernel with lengthscale `0.5 c`
```

2021-10-01 09:50 UTC, Cyberface commented on src/kernels/gibbskernel.jl
> +``l(x) = l`` then you recover the standard Squared-Exponential kernel
great thanks and that answers my other question about the square root / squaring about with_lengthscale

2021-10-01 09:52 UTC, Cyberface commented
> Just a comment for the docstring. And could you also add the kernel in the docs (just add the kernel name in the list in docs/kernels.md)?

Yeah sure thing. Shall I add a new section in `base kernels` called 'non-stationary kernels' ? Or shall I put it in 'Exponential Kernels' ?

2021-10-01 09:55 UTC, willtebbutt commented
I'd just put it in alphabetical order in the base kernels list. Feels like the appropriate place to me (the base kernels aren't necessarily stationary)

2021-10-01 10:31 UTC, Cyberface commented
great thanks - done!

2021-10-01 10:34 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
> I guess the 2 disappears because we already have l(x) + l(y) ?

I'm not sure what 2 you refer to (and there is no l(x) + l(y) term anywhere 🤔). The 2 in the square root outside of the squared exponential kernel disappears because we already scale the square root of the denominator by 1/sqrt(2).

> why we shouldn't square the argument to `with_lengthscale`

It will be squared by the squared exponential kernel. A squared exponential kernel with lengthscale l is of the form `k(x, y) = exp(- (x - y)^2/(2*l^2))`.

2021-10-01 10:38 UTC, Cyberface commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
So the `l(x) + l(y)` term I was refering to is the denominator in the exponential i.e.
`exp(-(x - y)^2 / (l(x)^2 + l(y)^2)`

And when `l(x) = l(y) = l = constant` you get `exp(-(x - y)^2 / (2l^2)` ?

Also thanks for explaining to me about the `with_lengthscale`

2021-10-01 10:40 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +``l(x) = l`` then you recover the standard Squared-Exponential kernel
The lengthscale is just `c`, it seems: In this case we get `exp(-(x-y)^2/(2*c^2))`, both with our implementation and the formula it is based on which corresponds to a lengthscale of `c`.

2021-10-01 11:14 UTC, devmotion requested changes

2021-10-01 11:14 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +For a constant function``l(x) = c``, one recovers the standard Squared-Exponential kernel with lengthscale `0.5 c`
See my comment above:
```suggestion
For a constant function``l(x) = c``, one recovers the standard squared exponential kernel with lengthscale `c`.
```

2021-10-01 11:15 UTC, devmotion commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) ≈ sqrt((2 * ell(x) * ell(y)) / (ell(x)^2 + ell(y)^2)) * exp(- norm(x - y)^2 / (ell(x)^2 + ell(y)^2))
No need for `norm` here:
```suggestion
    @test k_gibbs(x, y) ≈ sqrt((2 * ell(x) * ell(y)) / (ell(x)^2 + ell(y)^2)) * exp(-(x - y)^2 / (ell(x)^2 + ell(y)^2))
```

2021-10-01 11:33 UTC, Cyberface commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) ≈ sqrt((2 * ell(x) * ell(y)) / (ell(x)^2 + ell(y)^2)) * exp(- norm(x - y)^2 / (ell(x)^2 + ell(y)^2))
Ah ok - i suppose if we used something like `x=rand(2)` or something then we should use `norm` ?

2021-10-01 11:34 UTC, Cyberface commented on src/kernels/gibbskernel.jl
> +For a constant function``l(x) = c``, one recovers the standard Squared-Exponential kernel with lengthscale `0.5 c`
ah ok - thanks for thinking about this and figuring it out, it is a bit confusing :)

2021-10-01 11:35 UTC, devmotion commented on test/kernels/gibbskernel.jl
> +    @test k_gibbs(x, y) ≈ sqrt((2 * ell(x) * ell(y)) / (ell(x)^2 + ell(y)^2)) * exp(- norm(x - y)^2 / (ell(x)^2 + ell(y)^2))
Yes, if `x` and `y` would be vectors it would be needed.

2021-10-01 11:48 UTC, theogf commented on src/kernels/gibbskernel.jl
> +For a constant function``l(x) = c``, one recovers the standard Squared-Exponential kernel with lengthscale `0.5 c`
But no that's not true :) That's why we needed to divide by `sqrt(2)`

2021-10-01 11:54 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +    kernel = (sqrt(2 * lx * ly) / l) * with_lengthscale(SqExponentialKernel(), l)
Exactly, if they are constant you get `exp(-(x-y)^2 / (2 * l^2))`. Very explicitly, in general the implementation yields
```math
k(x, y) = sqrt(l(x) * l(y)) / (sqrt(l(x)^2 + l(y)^2) / sqrt(2)) * exp(- (x - y)^2 / (2 * (sqrt(l(x)^2 + l(y)^2) / sqrt(2))^2))
= sqrt(2 * l(x) * l(y) / (l(x)^2 + l(y)^2)) * exp(- (x - y)^2 / (l(x)^2 + l(y)^2))
```
which is exactly the formula in the docstring (and the other issue).

2021-10-01 11:55 UTC, Cyberface commented
The PR says there is a request to change something but I'm not sure what it's referring to.

2021-10-01 11:57 UTC, devmotion commented
> The PR says there is a request to change something but I'm not sure what it's referring to.

It was my request to fix the docstring.

2021-10-01 11:58 UTC, devmotion commented on test/kernels/gibbskernel.jl
> +end
Seems JuliaFormatter is not completely happy:
```suggestion
end
```

2021-10-01 12:03 UTC, devmotion reviewed
Some minor improvements to the docstring.

2021-10-01 12:03 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +    GibbsKernel(x, y)
```suggestion
    GibbsKernel(; lengthscale)
```

2021-10-01 12:03 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +The Gibbs kernel is non-stationary generalisation of the Squared-Exponential
```suggestion
The Gibbs kernel is non-stationary generalisation of the squared exponential
```

2021-10-01 12:03 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +with constant lengthscale ``l``.
```suggestion
For a constant function``l(x) = c``, one recovers the standard squared exponential kernel
with lengthscale `c`.
```

2021-10-01 12:03 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +k(x, y) = \\sqrt{ \\left(\\frac{2 l(x) l(y)}{l(x)^2 + l(y)^2} \\right) }
```suggestion
k(x, y; l) = \\sqrt{ \\left(\\frac{2 l(x) l(y)}{l(x)^2 + l(y)^2} \\right) }
```

2021-10-01 12:03 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +
```suggestion

# References

```

2021-10-01 12:03 UTC, devmotion commented on src/kernels/gibbskernel.jl
> +    "Neural Non-Stationary Spectral Kernel". arXiv:1811.10978, 2018
```suggestion
Mark N. Gibbs. "Bayesian Gaussian Processes for Regression and Classication." PhD thesis, 1997

Christopher J. Paciorek and Mark J. Schervish. "Nonstationary Covariance Functions
for Gaussian Process Regression". NeurIPS, 2003

Sami Remes, Markus Heinonen, Samuel Kaski. "Non-Stationary Spectral Kernels". arXiV:1705.08736, 2017

Sami Remes, Markus Heinonen, Samuel Kaski. "Neural Non-Stationary Spectral Kernel". arXiv:1811.10978, 2018
```

2021-10-01 12:05 UTC, devmotion approved these changes

2021-10-01 12:09 UTC, theogf commented
Great! All we need now is a version bump. In `Project.toml` can you change `version = "0.10.20"` to `version = "0.10.21"`

2021-10-01 12:46 UTC, merged

2021-10-01 12:46 UTC, devmotion commented
Thanks a lot @Cyberface!

2021-10-01 13:36 UTC, Cyberface commented
that's really great! Thanks so much for all your help with this! Next I'll work on getting the kernelmatrix working and eventually getting it so that the gibbs kernel length scale can be modelled with a separate GP and fit/optimise that!